import React from 'react';
import {Link, usePage} from '@inertiajs/react';
import UserAvatar from './UserAvatar';
import Icon from './Icon';
import bbuOfficialLogo from '../../assets/bbu-official-logo.png';

export default function AppSidebar({open, onClose, navigation, user, roles}) {
    const component = usePage().component;
    return <><button aria-label="Close navigation" onClick={onClose} className={`fixed inset-0 z-30 bg-slate-900/35 transition lg:hidden ${open ? 'block' : 'hidden'}`}/><aside className={`fixed inset-y-0 left-0 z-40 flex w-56 flex-col border-r border-slate-200 bg-white px-3 py-4 shadow-xl transition-transform duration-200 lg:translate-x-0 lg:shadow-none ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center gap-2.5 px-2"><img src={bbuOfficialLogo} alt="Build Bright University" className="h-11 w-9 shrink-0 object-contain"/><div><p className="font-bold tracking-tight text-slate-900">BBU</p><p className="text-[10px] font-semibold tracking-wide text-slate-500">ONLINE LEARNING</p></div><button onClick={onClose} className="ml-auto rounded-lg p-1.5 text-slate-500 hover:bg-sky-50 focus:outline-none focus:ring-2 focus:ring-sky-600 lg:hidden" aria-label="Close menu">×</button></div><nav aria-label="Primary navigation" className="mt-6 flex-1 space-y-4 overflow-y-auto">{navigation.map((group) => <section key={group.label}><p className="px-2 text-[10px] font-bold uppercase tracking-wider text-slate-400">{group.label}</p><div className="mt-1.5 space-y-0.5">{group.items.map((item) => item.href ? <Link onClick={onClose} key={item.label} href={item.href} className={`relative flex min-h-9 items-center gap-2.5 rounded-lg px-2.5 text-[13px] font-semibold transition ${component === item.component ? 'bg-sky-50 text-sky-800 before:absolute before:inset-y-1.5 before:left-0 before:w-0.5 before:rounded-full before:bg-sky-700' : 'text-slate-600 hover:bg-sky-50/70 hover:text-sky-800'}`}><span className={`inline-flex h-6 w-6 items-center justify-center rounded-md ${component === item.component ? 'text-sky-700' : 'text-slate-500'}`}><Icon name={item.icon} className="h-4 w-4"/></span>{item.label}{item.badge > 0 && <span className="ml-auto rounded-full bg-rose-600 px-1.5 py-0.5 text-[10px] text-white">{item.badge > 99 ? '99+' : item.badge}</span>}</Link> : <p key={item.label} className="flex min-h-9 items-center gap-2.5 rounded-lg px-2.5 text-[13px] text-slate-400"><span className="inline-flex h-6 w-6 items-center justify-center rounded-md"><Icon name={item.icon} className="h-4 w-4"/></span>{item.label}</p>)}</div></section>)}</nav><div className="rounded-xl border border-slate-200 bg-slate-50/70 p-2.5"><div className="flex items-center gap-2.5"><UserAvatar name={user.name} size="sm"/><div className="min-w-0"><p className="truncate text-xs font-bold text-slate-800">{user.name}</p><p className="truncate text-[10px] text-slate-500">{roles.join(', ')}</p></div></div><Link href="/logout" method="post" as="button" className="mt-2.5 flex w-full items-center gap-2 rounded-lg px-1 py-1.5 text-left text-xs font-bold text-rose-600 hover:bg-rose-50 focus:outline-none focus:ring-2 focus:ring-rose-500"><Icon name="logout" className="h-3.5 w-3.5"/>Sign out</Link></div></aside></>;
}
