import React from 'react';
import {Head, Link} from '@inertiajs/react';
import Layout from '../../Layouts/AuthenticatedLayout';
import Icon from '../../Components/UI/Icon';
import EmptyState from '../../Components/UI/EmptyState';
import JoinOrCreateClassPanel from '../../Components/Classes/JoinOrCreateClassPanel';

export default function Index({classes, canCreateClass, canJoinClass, createClassOptions}) {
    return <Layout><Head title="Classes"/><div className="mx-auto max-w-7xl"><header className="bbu-page-hero rounded-3xl px-6 py-7 sm:px-8"><div className="flex flex-wrap items-start justify-between gap-5"><div className="flex items-start gap-4"><span className="bbu-primary-icon inline-flex h-12 w-12 items-center justify-center rounded-2xl text-white"><Icon name="school" className="h-6 w-6"/></span><div><p className="text-sm font-bold text-sky-700">Learning workspaces</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Classes</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-600">Open the class workspaces that are available to your current BBU role and relationships.</p></div></div><JoinOrCreateClassPanel canJoinClass={canJoinClass} canCreateClass={canCreateClass} createClassOptions={createClassOptions}/></div></header><section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-900">My classes</h2><p className="mt-1 text-sm text-slate-500">Only classes authorized for your account are listed.</p></div><span className="rounded-full bg-sky-50 px-3 py-1 text-xs font-bold text-sky-800">{classes.length} {classes.length === 1 ? 'workspace' : 'workspaces'}</span></div>{classes.length ? <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{classes.map((schoolClass, index) => <ClassCard key={schoolClass.id} schoolClass={schoolClass} tone={['navy', 'blue', 'amber', 'coral'][index % 4]}/>)}</div> : <div className="mt-5"><EmptyState text="No class workspaces are available for your current account. Contact BBU administration if you expect to be enrolled or assigned to a class."/></div>}</section></div></Layout>;
}

function ClassCard({schoolClass, tone}) {
    const tones = {navy: 'from-[#082f63] to-[#075ca8]', blue: 'from-sky-700 to-[#2380c8]', amber: 'from-amber-500 to-orange-400', coral: 'from-rose-600 to-pink-500'};
    return <Link href={schoolClass.workspaceUrl} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-sky-200 hover:shadow-lg hover:shadow-sky-100/70 focus:outline-none focus:ring-2 focus:ring-sky-600"><div className={`relative min-h-28 overflow-hidden bg-gradient-to-br p-5 text-white ${tones[tone]}`}><span className="absolute -right-7 -top-9 h-28 w-28 rounded-full bg-white/15"/><span className="absolute bottom-3 right-4 text-white/80"><Icon name="school" className="h-11 w-11"/></span><p className="relative text-xs font-bold uppercase tracking-wider text-white/80">{schoolClass.gradeLevel?.name || 'Class workspace'}</p><h3 className="relative mt-2 pr-9 text-xl font-bold leading-tight">{schoolClass.name}{schoolClass.section ? ` ${schoolClass.section}` : ''}</h3></div><div className="p-5"><p className="text-sm font-semibold text-slate-800">{schoolClass.academicYear?.name || 'Academic year not available'}</p><p className="mt-1 text-xs text-slate-500">{schoolClass.teacher?.name ? `Teacher · ${schoolClass.teacher.name}` : 'Teaching team not assigned'}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-xs font-bold text-sky-700">Open workspace</span>{schoolClass.memberCount !== null && <span className="inline-flex items-center gap-1 text-xs font-semibold text-slate-500"><Icon name="users" className="h-3.5 w-3.5"/>{schoolClass.memberCount}</span>}<Icon name="arrow-right" className="h-4 w-4 text-sky-700 transition group-hover:translate-x-0.5"/></div></div></Link>;
}
