import React from 'react';
import {Head} from '@inertiajs/react';
import Layout from '../../Layouts/AuthenticatedLayout';
import Icon from '../../Components/UI/Icon';
import EmptyState from '../../Components/UI/EmptyState';
import JoinOrCreateClassPanel from '../../Components/Classes/JoinOrCreateClassPanel';
import ClassCard, {classCardTones} from '../../Components/Classes/ClassCard';

export default function Index({classes, canCreateClass, canJoinClass, createClassOptions}) {
    return <Layout><Head title="Classes"/><div className="mx-auto max-w-7xl"><header className="bbu-page-hero rounded-3xl px-6 py-7 sm:px-8"><div className="flex flex-wrap items-start justify-between gap-5"><div className="flex items-start gap-4"><span className="bbu-primary-icon inline-flex h-12 w-12 items-center justify-center rounded-2xl text-white"><Icon name="school" className="h-6 w-6"/></span><div><p className="text-sm font-bold text-sky-700">Learning workspaces</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Classes</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-600">Open the class workspaces that are available to your current BBU role and relationships.</p></div></div><JoinOrCreateClassPanel canJoinClass={canJoinClass} canCreateClass={canCreateClass} createClassOptions={createClassOptions}/></div></header><section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-900">My classes</h2><p className="mt-1 text-sm text-slate-500">Only classes authorized for your account are listed.</p></div><span className="rounded-full bg-sky-50 px-3 py-1 text-xs font-bold text-sky-800">{classes.length} {classes.length === 1 ? 'workspace' : 'workspaces'}</span></div>{classes.length ? <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{classes.map((schoolClass, index) => <ClassCard key={schoolClass.id} schoolClass={schoolClass} tone={classCardTones[index % classCardTones.length]} actionLabel="Open workspace" count={schoolClass.memberCount}/>)}</div> : <div className="mt-5"><EmptyState text="No class workspaces are available for your current account. Contact BBU administration if you expect to be enrolled or assigned to a class."/></div>}</section></div></Layout>;
}
