import React from 'react';
import {Head, Link, router} from '@inertiajs/react';
import Layout from '../../Layouts/AuthenticatedLayout';
import UserAvatar from '../../Components/UI/UserAvatar';

const Badge = ({children, tone = 'slate'}) => <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${tone === 'green' ? 'bg-emerald-50 text-emerald-700' : tone === 'amber' ? 'bg-amber-50 text-amber-700' : tone === 'blue' ? 'bg-sky-50 text-sky-700' : tone === 'red' ? 'bg-rose-50 text-rose-700' : 'bg-slate-100 text-slate-700'}`}>{children}</span>;

export default function Index({users, filters, roles}) {
    const update = (key, value) => router.get('/users', {...filters, [key]: value || undefined}, {preserveState: true, replace: true});
    const approve = user => window.confirm(`Approve ${user.name}'s account?`) && router.post(`/users/${user.id}/approve`);
    const resetPassword = user => window.confirm(`Reset password for ${user.name}?\n\nThis assigns the temporary BBU password. The user must create a new password after login.`) && router.post(`/users/${user.id}/reset-password`);

    return <Layout><Head title="Users & Permissions"/>
        <section className="rounded-3xl border border-sky-100 bg-gradient-to-br from-sky-50 via-white to-blue-50 p-6 shadow-sm">
            <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-sky-700">Administration</p><h1 className="mt-1 text-2xl font-black text-slate-900">Users & permissions</h1><p className="mt-1 text-sm text-slate-600">Manage authorized accounts, account readiness, and roles.</p></div><div className="flex gap-2"><Link className="rounded-xl border border-sky-200 bg-white px-4 py-2.5 text-sm font-bold text-sky-800" href="/administration/roles">Roles</Link><Link className="btn" href="/users/create">Create user</Link></div></div>
            <div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><input className="field" defaultValue={filters.search} onChange={e => update('search', e.target.value)} placeholder="Search name or email"/><select className="field" value={filters.role || ''} onChange={e => update('role', e.target.value)}><option value="">All roles</option>{roles.map(role => <option key={role}>{role}</option>)}</select><select className="field" value={filters.status || ''} onChange={e => update('status', e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></select><select className="field" value={filters.approval || ''} onChange={e => update('approval', e.target.value)}><option value="">Any approval</option><option value="approved">Approved</option><option value="pending">Pending</option></select><select className="field" value={filters.password_status || ''} onChange={e => update('password_status', e.target.value)}><option value="">Any password state</option><option value="normal">Normal</option><option value="change-required">Change required</option></select><select className="field" value={filters.verified || ''} onChange={e => update('verified', e.target.value)}><option value="">Any verification</option><option value="yes">Verified</option><option value="no">Unverified</option></select></div>
        </section>
        <section className="mt-5 overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1040px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">User</th><th>Roles</th><th>Account</th><th>Approval</th><th>Password</th><th>Verified</th><th className="pr-5 text-right">Actions</th></tr></thead><tbody>{users.data.map(user => <tr key={user.id} className="border-t border-slate-100"><td className="px-5 py-4"><div className="flex items-center gap-3"><UserAvatar name={user.name} avatarUrl={user.avatar_url} size="sm"/><div><p className="font-bold text-slate-900">{user.name}</p><p className="text-xs text-slate-500">{user.email}</p></div></div></td><td>{user.roles.map(role => <span className="mr-1 inline-flex rounded-full bg-indigo-50 px-2 py-1 text-xs font-bold text-indigo-700" key={role}>{role}</span>)}</td><td><Badge tone={user.status === 'active' ? 'green' : user.status === 'suspended' ? 'red' : 'amber'}>{user.status}</Badge></td><td><Badge tone={user.approval === 'approved' ? 'green' : 'amber'}>{user.approval}</Badge></td><td><Badge tone={user.password_status === 'normal' ? 'blue' : 'amber'}>{user.password_status === 'normal' ? 'Normal' : 'Change required'}</Badge></td><td>{user.verified_at ? <Badge tone="green">Verified</Badge> : <Badge tone="amber">Unverified</Badge>}</td><td className="pr-5 text-right"><div className="flex justify-end gap-2"><Link className="font-bold text-sky-700" href={`/users/${user.id}/edit`}>Manage</Link>{user.can_approve && user.approval === 'pending' && <button type="button" className="font-bold text-emerald-700" onClick={() => approve(user)}>Approve</button>}{user.can_reset_password && <button type="button" className="font-bold text-rose-700" onClick={() => resetPassword(user)}>Reset password</button>}</div></td></tr>)}</tbody></table></div></section>
    </Layout>;
}
