import React, {useMemo, useState} from 'react';
import {Head, Link, router, useForm} from '@inertiajs/react';
import Layout from '../../Layouts/AuthenticatedLayout';
import Icon from '../../Components/UI/Icon';
import SectionCard from '../../Components/UI/SectionCard';
import StatusBadge from '../../Components/UI/StatusBadge';
import attendanceEmpty from '../../assets/edway-empty-attendance.svg';
import {useTranslation} from '../../i18n/LocaleProvider';

const today = new Date().toISOString().slice(0, 10);
const statusOptions = ['present', 'absent', 'late', 'excused'];
const statusLabelKeys = {present: 'attendance.present', absent: 'attendance.absent', late: 'attendance.late', excused: 'attendance.excused'};

export default function Index({classes, students, registers, filters, report_url: reportUrl, report_export_url: reportExportUrl}) {
    const {t} = useTranslation();
    const initialFilters = useMemo(() => ({school_class_id: filters.school_class_id || '', academic_year_id: filters.academic_year_id || '', student_profile_id: filters.student_profile_id || '', date_from: filters.date_from || '', date_to: filters.date_to || ''}), [filters]);
    const [history, setHistory] = useState(initialFilters);
    const [historyLoading, setHistoryLoading] = useState(false);
    const [historyError, setHistoryError] = useState('');
    const [reportFilters, setReportFilters] = useState({...initialFilters, status: ''});
    const [report, setReport] = useState(null);
    const [reportLoading, setReportLoading] = useState(false);
    const [reportError, setReportError] = useState('');
    const open = useForm({attendance_date: today, school_class_id: ''});
    const openableClasses = classes.filter((schoolClass) => schoolClass.can_open);
    const update = (setter, key, value) => setter((current) => ({...current, [key]: value}));
    const requestHistory = (event) => { event.preventDefault(); setHistoryError(''); router.get('/attendance', compact(history), {preserveState: true, replace: true, onStart: () => setHistoryLoading(true), onError: () => setHistoryError(t('attendance.historyLoadFailed')), onFinish: () => setHistoryLoading(false)}); };
    const clearHistory = () => { const cleared = {school_class_id: '', academic_year_id: '', student_profile_id: '', date_from: '', date_to: ''}; setHistory(cleared); setHistoryError(''); router.get('/attendance', {}, {preserveState: true, replace: true, onStart: () => setHistoryLoading(true), onFinish: () => setHistoryLoading(false)}); };
    const openRegister = (event) => { event.preventDefault(); if (open.data.school_class_id) open.post(`/school-classes/${open.data.school_class_id}/attendance`); };
    const loadReport = async (event) => { event.preventDefault(); setReportLoading(true); setReportError(''); try { const response = await fetch(`${reportUrl}?${new URLSearchParams(compact(reportFilters)).toString()}`, {headers: {Accept: 'application/json', 'X-Requested-With': 'XMLHttpRequest'}, credentials: 'same-origin'}); if (!response.ok) throw new Error(response.status === 403 ? t('attendance.reportUnauthorized') : t('attendance.reportLoadFailed')); setReport(await response.json()); } catch (error) { setReportError(error.message || t('attendance.reportLoadFailed')); } finally { setReportLoading(false); } };

    return <Layout><Head title={t('attendance.title')}/>
        <PageHeader t={t}/>
        <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(330px,.72fr)]">
            <SectionCard icon="calendar" tone="mint" title={t('attendance.attendanceHistory')} description={t('attendance.attendanceHistoryDescription')}><form className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3" onSubmit={requestHistory}>
                <SelectField label={t('classes.title')} value={history.school_class_id} onChange={(value) => update(setHistory, 'school_class_id', value)}><option value="">{t('attendance.allClasses')}</option>{classes.map((schoolClass) => <option key={schoolClass.id} value={schoolClass.id}>{classLabel(schoolClass)}</option>)}</SelectField>                <SelectField label={t('classes.academicYear')} value={history.academic_year_id} onChange={(value) => update(setHistory, 'academic_year_id', value)}><option value="">{t('attendance.allAcademicYears')}</option>{academicYears(classes).map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</SelectField>                <SelectField label={t('attendance.student')} value={history.student_profile_id} onChange={(value) => update(setHistory, 'student_profile_id', value)}><option value="">{t('attendance.allStudents')}</option>{students.map((student) => <option key={student.id} value={student.id}>{student.name}{student.student_number ? ` · ${student.student_number}` : ''}</option>)}</SelectField>                <Field label={t('attendance.from')}><input className="field" type="date" value={history.date_from} onChange={(event) => update(setHistory, 'date_from', event.target.value)}/></Field><Field label={t('attendance.to')}><input className="field" type="date" value={history.date_to} onChange={(event) => update(setHistory, 'date_to', event.target.value)}/></Field><div className="flex items-end gap-2"><button className="btn flex-1" disabled={historyLoading}>{historyLoading ? t('attendance.loading') : t('attendance.applyFilters')}</button><button type="button" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-50" onClick={clearHistory}>{t('attendance.clear')}</button></div>
            </form>{historyError && <Feedback>{historyError}</Feedback>}</SectionCard>
            {openableClasses.length > 0 && <SectionCard icon="clipboard" tone="lavender" title={t('attendance.openDailyRegister')} description={t('attendance.openDailyRegisterDescription')}><form className="grid gap-3 sm:grid-cols-2" onSubmit={openRegister}><SelectField label={t('classes.title')} value={open.data.school_class_id} onChange={(value) => open.setData('school_class_id', value)} required><option value="">{t('attendance.selectAClass')}</option>{openableClasses.map((schoolClass) => <option key={schoolClass.id} value={schoolClass.id}>{classLabel(schoolClass)}</option>)}</SelectField><Field label={t('attendance.date')}><input className="field" type="date" value={open.data.attendance_date} onChange={(event) => open.setData('attendance_date', event.target.value)} required/></Field><button className="btn sm:col-span-2" disabled={open.processing}>{open.processing ? t('attendance.openingRegister') : t('attendance.openAttendanceRegister')}</button>{open.errors.attendance_date && <Feedback>{open.errors.attendance_date}</Feedback>}</form></SectionCard>}
        </div>
        <section className="mt-7"><SectionTitle icon="users" title={t('attendance.availableRegisters')} description={t('attendance.availableRegistersDescription')}/><div className="grid gap-4">{historyLoading && <LoadingCard label={t('attendance.historyLoading')}/>}{!historyLoading && registers.map((register) => <RegisterCard key={register.public_id} register={register}/>)}{!historyLoading && registers.length === 0 && <IllustratedEmpty label={hasFilters(history) ? t('attendance.noRegistersMatch') : t('attendance.noRegistersFound')} helper={hasFilters(history) ? t('attendance.noRegistersMatchHint') : t('attendance.noRegistersFoundHint')}/>}</div></section>
        <section className="mt-8"><SectionTitle icon="chart" title={t('attendance.attendanceReport')} description={t('attendance.attendanceReportDescription')}/><SectionCard icon="chart" tone="blue" title={t('attendance.reportFilters')} description={t('attendance.reportFiltersDescription')}><form className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3" onSubmit={loadReport}>
            <SelectField label={t('classes.title')} value={reportFilters.school_class_id} onChange={(value) => update(setReportFilters, 'school_class_id', value)}><option value="">{t('attendance.allClasses')}</option>{classes.map((schoolClass) => <option key={schoolClass.id} value={schoolClass.id}>{classLabel(schoolClass)}</option>)}</SelectField><SelectField label={t('classes.academicYear')} value={reportFilters.academic_year_id} onChange={(value) => update(setReportFilters, 'academic_year_id', value)}><option value="">{t('attendance.allAcademicYears')}</option>{academicYears(classes).map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</SelectField><SelectField label={t('attendance.student')} value={reportFilters.student_profile_id} onChange={(value) => update(setReportFilters, 'student_profile_id', value)}><option value="">{t('attendance.allStudents')}</option>{students.map((student) => <option key={student.id} value={student.id}>{student.name}{student.student_number ? ` · ${student.student_number}` : ''}</option>)}</SelectField><Field label={t('attendance.from')}><input className="field" type="date" value={reportFilters.date_from} onChange={(event) => update(setReportFilters, 'date_from', event.target.value)}/></Field><Field label={t('attendance.to')}><input className="field" type="date" value={reportFilters.date_to} onChange={(event) => update(setReportFilters, 'date_to', event.target.value)}/></Field><SelectField label={t('attendance.status')} value={reportFilters.status} onChange={(value) => update(setReportFilters, 'status', value)}><option value="">{t('attendance.allStatuses')}</option>{statusOptions.map((status) => <option key={status} value={status}>{t(statusLabelKeys[status])}</option>)}</SelectField><div className="sm:col-span-2 xl:col-span-3 flex flex-wrap gap-2"><button className="btn" disabled={reportLoading}>{reportLoading ? t('attendance.preparingReport') : t('attendance.viewReport')}</button><button type="button" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-50" onClick={() => { setReportFilters({...initialFilters, status: ''}); setReport(null); setReportError(''); }}>{t('attendance.clearReport')}</button></div>
        </form>{reportError && <Feedback>{reportError}</Feedback>}</SectionCard><div className="mt-4">{reportLoading && <LoadingCard label={t('attendance.preparingReport')}/>}{report && !reportLoading && <ReportResults report={report} exportUrl={`${reportExportUrl}?${new URLSearchParams(compact(report.filters)).toString()}`}/>}</div></section>
    </Layout>;
}

function PageHeader({t}) { return <header className="mb-6 rounded-3xl border border-indigo-100 bg-gradient-to-br from-white via-indigo-50/55 to-violet-50 px-6 py-6 shadow-sm sm:px-8"><div className="flex items-start gap-4"><span className="inline-flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-indigo-600 text-white shadow-lg shadow-indigo-200"><Icon name="calendar" className="h-6 w-6"/></span><div><p className="text-sm font-semibold text-indigo-600">{t('attendance.dailyRegister')}</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">{t('attendance.title')}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t('attendance.attendanceHistoryDescription')}</p></div></div></header>; }
function SectionTitle({icon, title, description}) { return <div className="mb-3 flex items-center gap-2"><span className="inline-flex h-8 w-8 items-center justify-center rounded-lg edway-tone-blue text-sky-700"><Icon name={icon} className="h-4 w-4"/></span><div><h2 className="font-bold text-slate-900">{title}</h2><p className="text-sm text-slate-500">{description}</p></div></div>; }
function Field({label, children}) { return <label className="min-w-0 text-sm font-semibold text-slate-700"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function SelectField({label, value, onChange, children, required = false}) { return <Field label={label}><select className="field w-full" value={value} onChange={(event) => onChange(event.target.value)} required={required}>{children}</select></Field>; }
function Feedback({children}) { return <p className="mt-3 rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-sm font-medium text-rose-700">{children}</p>; }
function LoadingCard({label}) { return <div className="edway-card flex min-h-32 items-center justify-center gap-3 p-6 text-sm font-semibold text-indigo-700"><span className="h-5 w-5 animate-spin rounded-full border-2 border-indigo-200 border-t-indigo-600"/>{label}</div>; }
function RegisterCard({register}) { const {t} = useTranslation(); return <Link className="edway-card group block p-5 transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-indigo-300" href={`/school-classes/${register.school_class.id}/attendance/${register.public_id}`}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-3"><span className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl edway-tone-lavender text-indigo-700"><Icon name="school" className="h-5 w-5"/></span><div><p className="text-sm text-slate-500">{register.school_class.grade_level?.name} · {register.school_class.academic_year?.name}</p><h3 className="mt-0.5 text-lg font-bold text-slate-900">{register.school_class.name} {register.school_class.section}</h3><p className="mt-1 flex items-center gap-1.5 text-sm font-medium text-slate-600"><Icon name="calendar" className="h-4 w-4 text-indigo-500"/>{register.attendance_date}</p></div></div><div className="flex items-center gap-3"><StatusBadge value={register.status}/><Icon name="spark" className="h-4 w-4 text-indigo-400 transition group-hover:text-indigo-600"/></div></div><dl className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5"><Count label="Present" labelText={t('attendance.present')} value={register.present_count}/><Count label="Absent" labelText={t('attendance.absent')} value={register.absent_count}/><Count label="Late" labelText={t('attendance.late')} value={register.late_count}/><Count label="Excused" labelText={t('attendance.excused')} value={register.excused_count}/><Count label="Roster" labelText={t('attendance.roster')} value={register.total_roster_count}/></dl></Link>; }
function Count({label, labelText, value}) { const icons = {Present: 'present', Absent: 'absent', Late: 'late', Excused: 'excused', Roster: 'total'}; return <div className={`rounded-xl p-3 ${attendanceTone(label)}`}><span className="inline-flex h-7 w-7 items-center justify-center rounded-lg bg-white/75"><Icon name={icons[label]} className="h-4 w-4"/></span><dt className="mt-2 text-sm text-slate-600">{labelText}</dt><dd className="mt-1 text-xl font-bold text-slate-900">{value ?? 0}</dd></div>; }
function ReportResults({report, exportUrl}) { const {t} = useTranslation(); const totals = report.totals || {}; const context = report.context || {}; return <SectionCard icon="chart" tone="lavender" title={t('attendance.studentAttendance')} description={t('attendance.totalsReflectFilters')} action={<a className="btn inline-flex items-center gap-2" href={exportUrl}><Icon name="download" className="h-4 w-4"/>{t('attendance.exportCsv')}</a>}><div className="mb-5 flex flex-wrap gap-2 text-xs font-semibold text-slate-600"><ContextPill label={t('classes.title')} value={context.class_name ? `${context.class_name}${context.class_section ? ` ${context.class_section}` : ''}` : t('attendance.allAuthorizedClasses')}/><ContextPill label={t('classes.academicYear')} value={context.academic_year_name || t('attendance.allAuthorizedAcademicYears')}/><ContextPill label={t('attendance.dateRange')} value={dateRange(report.filters, t)}/></div><dl className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-5"><Count label="Present" value={totals.present}/><Count label="Absent" value={totals.absent}/><Count label="Late" value={totals.late}/><Count label="Excused" value={totals.excused}/><Count label="Records" value={totals.records}/></dl>{report.students?.length > 0 ? <div className="-mx-6 -mb-6 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-y border-indigo-50 bg-indigo-50/45 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-3">{t('attendance.studentName')}</th><th className="px-3 py-3">{t('attendance.total')}</th><th className="px-3 py-3">{t('attendance.present')}</th><th className="px-3 py-3">{t('attendance.absent')}</th><th className="px-3 py-3">{t('attendance.late')}</th><th className="px-3 py-3">{t('attendance.excused')}</th><th className="px-6 py-3">{t('attendance.attendancePercent')}</th></tr></thead><tbody>{report.students.map((entry) => <tr key={entry.student.id} className="border-b border-slate-100"><td className="px-6 py-4"><p className="font-bold text-slate-900">{entry.student.name}</p>{entry.student.student_number && <p className="text-xs text-slate-500">{entry.student.student_number}</p>}</td><td className="px-3 py-4">{entry.total}</td><td className="px-3 py-4 text-emerald-700">{entry.present}</td><td className="px-3 py-4 text-rose-700">{entry.absent}</td><td className="px-3 py-4 text-amber-700">{entry.late}</td><td className="px-3 py-4 text-sky-700">{entry.excused}</td><td className="px-6 py-4 font-bold text-indigo-700">{Number(entry.attendance_percentage || 0).toFixed(1)}%</td></tr>)}</tbody></table></div> : <IllustratedEmpty label={t('attendance.noStudentsMatchReport')} helper={t('attendance.noStudentsMatchReportHint')}/>}</SectionCard>; }
function ContextPill({label, value}) { return <span className="rounded-full border border-indigo-100 bg-white/80 px-3 py-1.5"><span className="text-slate-400">{label}: </span>{value}</span>; }
function IllustratedEmpty({label, helper}) { return <div className="edway-card flex min-h-56 flex-col items-center justify-center p-6 text-center"><img src={attendanceEmpty} alt="" className="h-24 w-36 object-contain"/><h3 className="mt-3 font-bold text-slate-800">{label}</h3><p className="mt-1 max-w-md text-sm leading-6 text-slate-500">{helper}</p></div>; }
function compact(values) { return Object.fromEntries(Object.entries(values).filter(([, value]) => value !== '' && value !== null && value !== undefined)); }
function academicYears(classes) { return classes.map((schoolClass) => schoolClass.academic_year).filter(Boolean).filter((year, index, list) => list.findIndex((candidate) => candidate.id === year.id) === index); }
function classLabel(schoolClass) { return `${schoolClass.name}${schoolClass.section ? ` ${schoolClass.section}` : ''}${schoolClass.academic_year?.name ? ` · ${schoolClass.academic_year.name}` : ''}`; }
function hasFilters(filters) { return Object.values(filters).some(Boolean); }
function dateRange(filters = {}, t = (key) => key) { if (filters.date_from && filters.date_to) return t('attendance.dateRangeBetween', {from: filters.date_from, to: filters.date_to}); if (filters.date_from) return t('attendance.dateRangeFrom', {date: filters.date_from}); if (filters.date_to) return t('attendance.dateRangeUntil', {date: filters.date_to}); return t('attendance.allDates'); }
function attendanceTone(label) { return {Present: 'edway-tone-mint', Absent: 'edway-tone-coral', Late: 'edway-tone-amber', Excused: 'edway-tone-blue'}[label] || 'edway-tone-lavender'; }
