import React, {useState} from 'react';
import {Head, Link, router, useForm} from '@inertiajs/react';
import Layout from '../../Layouts/AuthenticatedLayout';
import Icon from '../../Components/UI/Icon';
import SectionCard from '../../Components/UI/SectionCard';
import StatusBadge from '../../Components/UI/StatusBadge';
import attendanceEmpty from '../../assets/edway-empty-attendance.svg';

const today = new Date().toISOString().slice(0, 10);

export default function Index({classes, registers, filters}) {
    const [classId, setClassId] = useState(filters.school_class_id || '');
    const [attendanceDate, setAttendanceDate] = useState(filters.attendance_date || '');
    const openableClasses = classes.filter((schoolClass) => schoolClass.can_open);
    const open = useForm({attendance_date: today});
    const applyFilters = (event) => { event.preventDefault(); router.get('/attendance', {school_class_id: classId || undefined, attendance_date: attendanceDate || undefined}, {preserveState: true, replace: true}); };
    const openRegister = (event) => { event.preventDefault(); if (open.data.school_class_id) open.post(`/school-classes/${open.data.school_class_id}/attendance`); };

    return <Layout><Head title="Attendance"/>
        <PageHeader title="Attendance" description="Class registers available to you."/>
        <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(330px,.7fr)]">
            <SectionCard icon="calendar" tone="mint" title="Register workspace" description="Find an existing register or open one for an authorized class."><form className="grid gap-3 sm:grid-cols-2 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]" onSubmit={applyFilters}><Field label="Class"><select className="field" value={classId} onChange={(event) => setClassId(event.target.value)}><option value="">All accessible classes</option>{classes.map((schoolClass) => <option key={schoolClass.id} value={schoolClass.id}>{schoolClass.name} {schoolClass.section}</option>)}</select></Field><Field label="Date"><input className="field" type="date" value={attendanceDate} onChange={(event) => setAttendanceDate(event.target.value)}/></Field><button className="self-end rounded-xl border border-indigo-100 bg-indigo-50 px-4 py-2.5 text-sm font-bold text-indigo-700 transition hover:bg-indigo-100 focus:outline-none focus:ring-2 focus:ring-indigo-200">Apply filters</button></form></SectionCard>
            {openableClasses.length > 0 && <SectionCard icon="clipboard" tone="lavender" title="Open daily register" description="Creates or returns the authorized class register for the selected date."><form className="grid gap-3 sm:grid-cols-2" onSubmit={openRegister}><Field label="Class"><select className="field" value={open.data.school_class_id || ''} onChange={(event) => open.setData('school_class_id', event.target.value)} required><option value="">Select a class</option>{openableClasses.map((schoolClass) => <option key={schoolClass.id} value={schoolClass.id}>{schoolClass.name} {schoolClass.section}</option>)}</select></Field><Field label="Date"><input className="field" type="date" value={open.data.attendance_date} onChange={(event) => open.setData('attendance_date', event.target.value)} required/></Field><button className="btn sm:col-span-2" disabled={open.processing}>{open.processing ? 'Opening register…' : 'Open attendance register'}</button>{open.errors.attendance_date && <p className="sm:col-span-2 text-sm font-medium text-rose-700">{open.errors.attendance_date}</p>}</form></SectionCard>}
        </div>
        <section className="mt-7"><div className="mb-3 flex items-center gap-2"><span className="inline-flex h-8 w-8 items-center justify-center rounded-lg edway-tone-blue text-sky-700"><Icon name="users" className="h-4 w-4"/></span><div><h2 className="font-bold text-slate-900">Available registers</h2><p className="text-sm text-slate-500">Open a register to record attendance, finalize it, or review approved corrections.</p></div></div><div className="grid gap-4">{registers.map((register) => <RegisterCard key={register.public_id} register={register}/>)}{registers.length === 0 && <IllustratedEmpty/>}</div></section>
    </Layout>;
}

function PageHeader({title, description}) { return <header className="mb-6 rounded-3xl border border-indigo-100 bg-gradient-to-br from-white via-indigo-50/55 to-violet-50 px-6 py-6 shadow-sm sm:px-8"><div className="flex items-start gap-4"><span className="inline-flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-indigo-600 text-white shadow-lg shadow-indigo-200"><Icon name="calendar" className="h-6 w-6"/></span><div><p className="text-sm font-semibold text-indigo-600">Daily class register</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{description}</p></div></div></header>; }
function Field({label, children}) { return <label className="text-sm font-semibold text-slate-700"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function RegisterCard({register}) { return <Link className="edway-card group block p-5 transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-indigo-300" href={`/school-classes/${register.school_class.id}/attendance/${register.public_id}`}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-3"><span className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl edway-tone-lavender text-indigo-700"><Icon name="school" className="h-5 w-5"/></span><div><p className="text-sm text-slate-500">{register.school_class.grade_level?.name} · {register.school_class.academic_year?.name}</p><h3 className="mt-0.5 text-lg font-bold text-slate-900">{register.school_class.name} {register.school_class.section}</h3><p className="mt-1 flex items-center gap-1.5 text-sm font-medium text-slate-600"><Icon name="calendar" className="h-4 w-4 text-indigo-500"/>{register.attendance_date}</p></div></div><div className="flex items-center gap-3"><StatusBadge value={register.status}/><Icon name="spark" className="h-4 w-4 text-indigo-400 transition group-hover:text-indigo-600"/></div></div><dl className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5"><Count label="Present" value={register.present_count}/><Count label="Absent" value={register.absent_count}/><Count label="Late" value={register.late_count}/><Count label="Excused" value={register.excused_count}/><Count label="Roster" value={register.total_roster_count}/></dl></Link>; }
function Count({label, value}) { const icons = {Present: 'present', Absent: 'absent', Late: 'late', Excused: 'excused', Roster: 'total'}; return <div className={`rounded-xl p-3 ${attendanceTone(label)}`}><span className="inline-flex h-7 w-7 items-center justify-center rounded-lg bg-white/75"><Icon name={icons[label]} className="h-4 w-4"/></span><dt className="mt-2 text-sm text-slate-600">{label}</dt><dd className="mt-1 text-xl font-bold text-slate-900">{value ?? 0}</dd></div>; }
function IllustratedEmpty() { return <div className="edway-card flex min-h-64 flex-col items-center justify-center text-center"><img src={attendanceEmpty} alt="" className="h-28 w-40 object-contain"/><h3 className="mt-3 font-bold text-slate-800">No attendance registers found</h3><p className="mt-1 max-w-md text-sm leading-6 text-slate-500">Open a register for an authorized class, or adjust the filters.</p></div>; }
function attendanceTone(label) { return {Present: 'edway-tone-mint', Absent: 'edway-tone-coral', Late: 'edway-tone-amber', Excused: 'edway-tone-blue'}[label] || 'edway-tone-lavender'; }
