import React, {useMemo, useState} from 'react';
import {Head, Link, router, useForm} from '@inertiajs/react';
import Layout from '../../Layouts/AuthenticatedLayout';
import Icon from '../../Components/UI/Icon';
import SectionCard from '../../Components/UI/SectionCard';
import StatusBadge from '../../Components/UI/StatusBadge';
import attendanceEmpty from '../../assets/edway-empty-attendance.svg';

const today = new Date().toISOString().slice(0, 10);
const statusOptions = ['present', 'absent', 'late', 'excused'];

export default function Index({classes, students, registers, filters, report_url: reportUrl, report_export_url: reportExportUrl}) {
    const initialFilters = useMemo(() => ({school_class_id: filters.school_class_id || '', academic_year_id: filters.academic_year_id || '', student_profile_id: filters.student_profile_id || '', date_from: filters.date_from || '', date_to: filters.date_to || ''}), [filters]);
    const [history, setHistory] = useState(initialFilters);
    const [historyLoading, setHistoryLoading] = useState(false);
    const [historyError, setHistoryError] = useState('');
    const [reportFilters, setReportFilters] = useState({...initialFilters, status: ''});
    const [report, setReport] = useState(null);
    const [reportLoading, setReportLoading] = useState(false);
    const [reportError, setReportError] = useState('');
    const open = useForm({attendance_date: today, school_class_id: ''});
    const openableClasses = classes.filter((schoolClass) => schoolClass.can_open);
    const update = (setter, key, value) => setter((current) => ({...current, [key]: value}));
    const requestHistory = (event) => { event.preventDefault(); setHistoryError(''); router.get('/attendance', compact(history), {preserveState: true, replace: true, onStart: () => setHistoryLoading(true), onError: () => setHistoryError('Attendance history could not be loaded. Please try again.'), onFinish: () => setHistoryLoading(false)}); };
    const clearHistory = () => { const cleared = {school_class_id: '', academic_year_id: '', student_profile_id: '', date_from: '', date_to: ''}; setHistory(cleared); setHistoryError(''); router.get('/attendance', {}, {preserveState: true, replace: true, onStart: () => setHistoryLoading(true), onFinish: () => setHistoryLoading(false)}); };
    const openRegister = (event) => { event.preventDefault(); if (open.data.school_class_id) open.post(`/school-classes/${open.data.school_class_id}/attendance`); };
    const loadReport = async (event) => { event.preventDefault(); setReportLoading(true); setReportError(''); try { const response = await fetch(`${reportUrl}?${new URLSearchParams(compact(reportFilters)).toString()}`, {headers: {Accept: 'application/json', 'X-Requested-With': 'XMLHttpRequest'}, credentials: 'same-origin'}); if (!response.ok) throw new Error(response.status === 403 ? 'You are not authorized to view this attendance report.' : 'The attendance report could not be loaded.'); setReport(await response.json()); } catch (error) { setReportError(error.message || 'The attendance report could not be loaded.'); } finally { setReportLoading(false); } };

    return <Layout><Head title="Attendance"/>
        <PageHeader/>
        <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(330px,.72fr)]">
            <SectionCard icon="calendar" tone="mint" title="Attendance history" description="Filters only return registers and students you are authorized to review."><form className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3" onSubmit={requestHistory}>
                <SelectField label="Class" value={history.school_class_id} onChange={(value) => update(setHistory, 'school_class_id', value)}><option value="">All accessible classes</option>{classes.map((schoolClass) => <option key={schoolClass.id} value={schoolClass.id}>{classLabel(schoolClass)}</option>)}</SelectField><SelectField label="Academic year" value={history.academic_year_id} onChange={(value) => update(setHistory, 'academic_year_id', value)}><option value="">All academic years</option>{academicYears(classes).map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</SelectField><SelectField label="Student" value={history.student_profile_id} onChange={(value) => update(setHistory, 'student_profile_id', value)}><option value="">All eligible students</option>{students.map((student) => <option key={student.id} value={student.id}>{student.name}{student.student_number ? ` · ${student.student_number}` : ''}</option>)}</SelectField><Field label="From"><input className="field" type="date" value={history.date_from} onChange={(event) => update(setHistory, 'date_from', event.target.value)}/></Field><Field label="To"><input className="field" type="date" value={history.date_to} onChange={(event) => update(setHistory, 'date_to', event.target.value)}/></Field><div className="flex items-end gap-2"><button className="btn flex-1" disabled={historyLoading}>{historyLoading ? 'Loading…' : 'Apply filters'}</button><button type="button" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-50" onClick={clearHistory}>Clear</button></div>
            </form>{historyError && <Feedback>{historyError}</Feedback>}</SectionCard>
            {openableClasses.length > 0 && <SectionCard icon="clipboard" tone="lavender" title="Open daily register" description="Creates or returns the authorized register for the selected class and date."><form className="grid gap-3 sm:grid-cols-2" onSubmit={openRegister}><SelectField label="Class" value={open.data.school_class_id} onChange={(value) => open.setData('school_class_id', value)} required><option value="">Select a class</option>{openableClasses.map((schoolClass) => <option key={schoolClass.id} value={schoolClass.id}>{classLabel(schoolClass)}</option>)}</SelectField><Field label="Date"><input className="field" type="date" value={open.data.attendance_date} onChange={(event) => open.setData('attendance_date', event.target.value)} required/></Field><button className="btn sm:col-span-2" disabled={open.processing}>{open.processing ? 'Opening register…' : 'Open attendance register'}</button>{open.errors.attendance_date && <Feedback>{open.errors.attendance_date}</Feedback>}</form></SectionCard>}
        </div>
        <section className="mt-7"><SectionTitle icon="users" title="Available registers" description="Open an authorized register to record attendance, finalize it, or review correction history."/><div className="grid gap-4">{historyLoading && <LoadingCard label="Loading attendance history…"/>}{!historyLoading && registers.map((register) => <RegisterCard key={register.public_id} register={register}/>)}{!historyLoading && registers.length === 0 && <IllustratedEmpty label={hasFilters(history) ? 'No registers match these filters' : 'No attendance registers found'} helper={hasFilters(history) ? 'Try clearing a filter or choosing another authorized class or date range.' : 'Open a register for an authorized class, or adjust the filters.'}/>}</div></section>
        <section className="mt-8"><SectionTitle icon="chart" title="Attendance report" description="Per-student totals are calculated by the same server-authorized data source used for CSV export."/><SectionCard icon="chart" tone="blue" title="Report filters" description="Choose a date range or leave filters broad to summarize your authorized attendance history."><form className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3" onSubmit={loadReport}>
            <SelectField label="Class" value={reportFilters.school_class_id} onChange={(value) => update(setReportFilters, 'school_class_id', value)}><option value="">All accessible classes</option>{classes.map((schoolClass) => <option key={schoolClass.id} value={schoolClass.id}>{classLabel(schoolClass)}</option>)}</SelectField><SelectField label="Academic year" value={reportFilters.academic_year_id} onChange={(value) => update(setReportFilters, 'academic_year_id', value)}><option value="">All academic years</option>{academicYears(classes).map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</SelectField><SelectField label="Student" value={reportFilters.student_profile_id} onChange={(value) => update(setReportFilters, 'student_profile_id', value)}><option value="">All eligible students</option>{students.map((student) => <option key={student.id} value={student.id}>{student.name}{student.student_number ? ` · ${student.student_number}` : ''}</option>)}</SelectField><Field label="From"><input className="field" type="date" value={reportFilters.date_from} onChange={(event) => update(setReportFilters, 'date_from', event.target.value)}/></Field><Field label="To"><input className="field" type="date" value={reportFilters.date_to} onChange={(event) => update(setReportFilters, 'date_to', event.target.value)}/></Field><SelectField label="Status" value={reportFilters.status} onChange={(value) => update(setReportFilters, 'status', value)}><option value="">All statuses</option>{statusOptions.map((status) => <option key={status} value={status}>{capitalize(status)}</option>)}</SelectField><div className="sm:col-span-2 xl:col-span-3 flex flex-wrap gap-2"><button className="btn" disabled={reportLoading}>{reportLoading ? 'Preparing report…' : 'View report'}</button><button type="button" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-50" onClick={() => { setReportFilters({...initialFilters, status: ''}); setReport(null); setReportError(''); }}>Clear report</button></div>
        </form>{reportError && <Feedback>{reportError}</Feedback>}</SectionCard><div className="mt-4">{reportLoading && <LoadingCard label="Preparing attendance report…"/>}{report && !reportLoading && <ReportResults report={report} exportUrl={`${reportExportUrl}?${new URLSearchParams(compact(report.filters)).toString()}`}/>}</div></section>
    </Layout>;
}

function PageHeader() { return <header className="mb-6 rounded-3xl border border-indigo-100 bg-gradient-to-br from-white via-indigo-50/55 to-violet-50 px-6 py-6 shadow-sm sm:px-8"><div className="flex items-start gap-4"><span className="inline-flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-indigo-600 text-white shadow-lg shadow-indigo-200"><Icon name="calendar" className="h-6 w-6"/></span><div><p className="text-sm font-semibold text-indigo-600">Daily class register</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Attendance</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Review authorized class history, open daily registers, and prepare attendance summaries.</p></div></div></header>; }
function SectionTitle({icon, title, description}) { return <div className="mb-3 flex items-center gap-2"><span className="inline-flex h-8 w-8 items-center justify-center rounded-lg edway-tone-blue text-sky-700"><Icon name={icon} className="h-4 w-4"/></span><div><h2 className="font-bold text-slate-900">{title}</h2><p className="text-sm text-slate-500">{description}</p></div></div>; }
function Field({label, children}) { return <label className="min-w-0 text-sm font-semibold text-slate-700"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function SelectField({label, value, onChange, children, required = false}) { return <Field label={label}><select className="field w-full" value={value} onChange={(event) => onChange(event.target.value)} required={required}>{children}</select></Field>; }
function Feedback({children}) { return <p className="mt-3 rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-sm font-medium text-rose-700">{children}</p>; }
function LoadingCard({label}) { return <div className="edway-card flex min-h-32 items-center justify-center gap-3 p-6 text-sm font-semibold text-indigo-700"><span className="h-5 w-5 animate-spin rounded-full border-2 border-indigo-200 border-t-indigo-600"/>{label}</div>; }
function RegisterCard({register}) { return <Link className="edway-card group block p-5 transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-indigo-300" href={`/school-classes/${register.school_class.id}/attendance/${register.public_id}`}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-3"><span className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl edway-tone-lavender text-indigo-700"><Icon name="school" className="h-5 w-5"/></span><div><p className="text-sm text-slate-500">{register.school_class.grade_level?.name} · {register.school_class.academic_year?.name}</p><h3 className="mt-0.5 text-lg font-bold text-slate-900">{register.school_class.name} {register.school_class.section}</h3><p className="mt-1 flex items-center gap-1.5 text-sm font-medium text-slate-600"><Icon name="calendar" className="h-4 w-4 text-indigo-500"/>{register.attendance_date}</p></div></div><div className="flex items-center gap-3"><StatusBadge value={register.status}/><Icon name="spark" className="h-4 w-4 text-indigo-400 transition group-hover:text-indigo-600"/></div></div><dl className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5"><Count label="Present" value={register.present_count}/><Count label="Absent" value={register.absent_count}/><Count label="Late" value={register.late_count}/><Count label="Excused" value={register.excused_count}/><Count label="Roster" value={register.total_roster_count}/></dl></Link>; }
function Count({label, value}) { const icons = {Present: 'present', Absent: 'absent', Late: 'late', Excused: 'excused', Roster: 'total'}; return <div className={`rounded-xl p-3 ${attendanceTone(label)}`}><span className="inline-flex h-7 w-7 items-center justify-center rounded-lg bg-white/75"><Icon name={icons[label]} className="h-4 w-4"/></span><dt className="mt-2 text-sm text-slate-600">{label}</dt><dd className="mt-1 text-xl font-bold text-slate-900">{value ?? 0}</dd></div>; }
function ReportResults({report, exportUrl}) { const totals = report.totals || {}; const context = report.context || {}; return <SectionCard icon="chart" tone="lavender" title="Student attendance" description="Totals reflect the selected authorized filters." action={<a className="btn inline-flex items-center gap-2" href={exportUrl}><Icon name="download" className="h-4 w-4"/>Export CSV</a>}><div className="mb-5 flex flex-wrap gap-2 text-xs font-semibold text-slate-600"><ContextPill label="Class" value={context.class_name ? `${context.class_name}${context.class_section ? ` ${context.class_section}` : ''}` : 'All authorized classes'}/><ContextPill label="Academic year" value={context.academic_year_name || 'All authorized academic years'}/><ContextPill label="Date range" value={dateRange(report.filters)}/></div><dl className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-5"><Count label="Present" value={totals.present}/><Count label="Absent" value={totals.absent}/><Count label="Late" value={totals.late}/><Count label="Excused" value={totals.excused}/><Count label="Records" value={totals.records}/></dl>{report.students?.length > 0 ? <div className="-mx-6 -mb-6 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-y border-indigo-50 bg-indigo-50/45 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-3">Student</th><th className="px-3 py-3">Total</th><th className="px-3 py-3">Present</th><th className="px-3 py-3">Absent</th><th className="px-3 py-3">Late</th><th className="px-3 py-3">Excused</th><th className="px-6 py-3">Attendance %</th></tr></thead><tbody>{report.students.map((entry) => <tr key={entry.student.id} className="border-b border-slate-100"><td className="px-6 py-4"><p className="font-bold text-slate-900">{entry.student.name}</p>{entry.student.student_number && <p className="text-xs text-slate-500">{entry.student.student_number}</p>}</td><td className="px-3 py-4">{entry.total}</td><td className="px-3 py-4 text-emerald-700">{entry.present}</td><td className="px-3 py-4 text-rose-700">{entry.absent}</td><td className="px-3 py-4 text-amber-700">{entry.late}</td><td className="px-3 py-4 text-sky-700">{entry.excused}</td><td className="px-6 py-4 font-bold text-indigo-700">{Number(entry.attendance_percentage || 0).toFixed(1)}%</td></tr>)}</tbody></table></div> : <IllustratedEmpty label="No students match this report" helper="The CSV export remains available and safely contains its header row only."/>}</SectionCard>; }
function ContextPill({label, value}) { return <span className="rounded-full border border-indigo-100 bg-white/80 px-3 py-1.5"><span className="text-slate-400">{label}: </span>{value}</span>; }
function IllustratedEmpty({label, helper}) { return <div className="edway-card flex min-h-56 flex-col items-center justify-center p-6 text-center"><img src={attendanceEmpty} alt="" className="h-24 w-36 object-contain"/><h3 className="mt-3 font-bold text-slate-800">{label}</h3><p className="mt-1 max-w-md text-sm leading-6 text-slate-500">{helper}</p></div>; }
function compact(values) { return Object.fromEntries(Object.entries(values).filter(([, value]) => value !== '' && value !== null && value !== undefined)); }
function academicYears(classes) { return classes.map((schoolClass) => schoolClass.academic_year).filter(Boolean).filter((year, index, list) => list.findIndex((candidate) => candidate.id === year.id) === index); }
function classLabel(schoolClass) { return `${schoolClass.name}${schoolClass.section ? ` ${schoolClass.section}` : ''}${schoolClass.academic_year?.name ? ` · ${schoolClass.academic_year.name}` : ''}`; }
function hasFilters(filters) { return Object.values(filters).some(Boolean); }
function dateRange(filters = {}) { if (filters.date_from && filters.date_to) return `${filters.date_from} to ${filters.date_to}`; if (filters.date_from) return `From ${filters.date_from}`; if (filters.date_to) return `Until ${filters.date_to}`; return 'All dates'; }
function capitalize(value) { return value.charAt(0).toUpperCase() + value.slice(1); }
function attendanceTone(label) { return {Present: 'edway-tone-mint', Absent: 'edway-tone-coral', Late: 'edway-tone-amber', Excused: 'edway-tone-blue'}[label] || 'edway-tone-lavender'; }
