<?php

use App\Http\Controllers\AcademicController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\AssignmentGradeController;
use App\Http\Controllers\AssignmentSubmissionAttachmentController;
use App\Http\Controllers\AssignmentSubmissionController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\ConfirmablePasswordController;
use App\Http\Controllers\Auth\EmailVerificationController;
use App\Http\Controllers\Auth\PasswordResetController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\CalendarPageController;
use App\Http\Controllers\ChannelController;
use App\Http\Controllers\ChannelReadStateController;
use App\Http\Controllers\ClassJoinController;
use App\Http\Controllers\ClassWorkspaceController;
use App\Http\Controllers\CollaborationController;
use App\Http\Controllers\ConversationAttachmentController;
use App\Http\Controllers\ConversationCallController;
use App\Http\Controllers\ConversationController;
use App\Http\Controllers\ConversationMessageExperienceController;
use App\Http\Controllers\CourseworkController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ForcedPasswordChangeController;
use App\Http\Controllers\GlobalSearchController;
use App\Http\Controllers\LiveKitWebhookController;
use App\Http\Controllers\MeetingAttendanceController;
use App\Http\Controllers\MeetingController;
use App\Http\Controllers\MeetingExperienceController;
use App\Http\Controllers\MeetingJoinRequestController;
use App\Http\Controllers\MeetingLifecycleController;
use App\Http\Controllers\MeetingParticipantController;
use App\Http\Controllers\MeetingScreenShareRequestController;
use App\Http\Controllers\MeetingSeriesController;
use App\Http\Controllers\MeetingTokenController;
use App\Http\Controllers\MeetingWaitingRoomController;
use App\Http\Controllers\MessageAttachmentController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\MessageReactionController;
use App\Http\Controllers\MyAccountController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PeopleController;
use App\Http\Controllers\ReportingPeriodController;
use App\Http\Controllers\ResultsController;
use App\Http\Controllers\RoleManagementController;
use App\Http\Controllers\SchoolClassJoinCodeController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::post('/integrations/livekit/webhook', LiveKitWebhookController::class)
    ->middleware('throttle:livekit-webhooks')->name('integrations.livekit.webhook');

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->name('login.store');
    Route::get('/forgot-password', [PasswordResetController::class, 'request'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetController::class, 'email'])->middleware('throttle:3,1')->name('password.email');
    Route::get('/reset-password/{token}', [PasswordResetController::class, 'reset'])->name('password.reset');
    Route::post('/reset-password', [PasswordResetController::class, 'update'])->name('password.update');
});

Route::middleware(['auth', 'account.active'])->group(function () {
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::get('/set-password', [ForcedPasswordChangeController::class, 'show'])->name('password.initialize.show');
    Route::put('/set-password', [ForcedPasswordChangeController::class, 'update'])->name('password.initialize.update');
    Route::get('/verify-email', [EmailVerificationController::class, 'notice'])->name('verification.notice');
    Route::get('/verify-email/{id}/{hash}', [EmailVerificationController::class, 'verify'])->middleware('signed')->name('verification.verify');
    Route::post('/email/verification-notification', [EmailVerificationController::class, 'send'])->middleware('throttle:6,1')->name('verification.send');
    Route::get('/confirm-password', [ConfirmablePasswordController::class, 'show'])->name('password.confirm');
    Route::post('/confirm-password', [ConfirmablePasswordController::class, 'store'])->name('password.confirm.store');
});

Route::middleware(['auth', 'account.active', 'verified', 'password.change-required'])->group(function () {
    Route::get('/', fn () => redirect()->route('dashboard'));
    Route::get('/global-search', GlobalSearchController::class)->middleware('throttle:60,1')->name('global-search');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/calendar', CalendarPageController::class)
        ->name('calendar.index');
    Route::get('/calendar/events', CalendarController::class)->name('calendar.events');
    Route::get('/my-account', [MyAccountController::class, 'show'])->name('my-account.profile');
    Route::get('/my-account/{section}', [MyAccountController::class, 'show'])->whereIn('section', ['profile', 'security', 'notifications', 'appearance'])->name('my-account.show');
    Route::patch('/my-account/profile', [MyAccountController::class, 'updateProfile'])->name('my-account.profile.update');
    Route::post('/my-account/avatar', [MyAccountController::class, 'updateAvatar'])->name('my-account.avatar.update');
    Route::delete('/my-account/avatar', [MyAccountController::class, 'destroyAvatar'])->name('my-account.avatar.destroy');
    Route::put('/my-account/security', [MyAccountController::class, 'updatePassword'])->name('my-account.security.update');
    Route::put('/my-account/locale', [MyAccountController::class, 'updateLocale'])->name('my-account.locale.update');
    Route::get('/classes', [ClassWorkspaceController::class, 'index'])->name('classes.index');
    Route::post('/classes/join', [ClassJoinController::class, 'store'])->middleware('throttle:class-join-code')->name('classes.join');
    Route::get('/classes/{schoolClass}', [ClassWorkspaceController::class, 'show'])->name('classes.show');
    Route::get('/classes/{schoolClass}/members', [ClassWorkspaceController::class, 'members'])->name('classes.members');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::patch('/notifications/read-all', [NotificationController::class, 'readAll'])->name('notifications.read-all');
    Route::patch('/notifications/{notificationPublicId}/read', [NotificationController::class, 'read'])->name('notifications.read');
    Route::resource('users', UserController::class)->except('show');
    Route::get('/administration/roles', [RoleManagementController::class, 'index'])->name('roles.index');
    Route::put('/administration/roles/{role}/permissions', [RoleManagementController::class, 'update'])->middleware('password.confirm')->name('roles.permissions.update');
    Route::patch('/users/{user}/status', [UserController::class, 'status'])->name('users.status');
    Route::patch('/users/{user}/role', [UserController::class, 'role'])->middleware('password.confirm')->name('users.role');
    Route::post('/users/{user}/approve', [UserController::class, 'approve'])->middleware('password.confirm')->name('users.approve');
    Route::post('/users/{user}/reset-password', [UserController::class, 'resetPassword'])->middleware('password.confirm')->name('users.reset-password');
    Route::post('/users/{user}/verification', [UserController::class, 'resendVerification'])->name('users.verification');
    Route::get('/academics', [AcademicController::class, 'index'])->name('academics.index');
    Route::post('/reporting-periods', [ReportingPeriodController::class, 'store'])->name('reporting-periods.store');
    Route::patch('/reporting-periods/{reportingPeriod}', [ReportingPeriodController::class, 'update'])->name('reporting-periods.update');
    Route::patch('/reporting-periods/{reportingPeriod}/transition', [ReportingPeriodController::class, 'transition'])->name('reporting-periods.transition');
    Route::get('/results', [ResultsController::class, 'index'])->name('results.index');
    Route::get('/results/{reportingPeriod}/school-classes/{schoolClass}/class-subjects/{classSubject}', [ResultsController::class, 'show'])->name('results.show');
    Route::get('/my-results', [ResultsController::class, 'mine'])->name('results.mine');
    Route::get('/my-results/reporting-periods/{reportingPeriod}/school-classes/{schoolClass}', [ResultsController::class, 'reportCard'])->name('results.report-card');
    Route::post('/academic-years', [AcademicController::class, 'storeYear'])->name('academic-years.store');
    Route::patch('/academic-years/{academicYear}', [AcademicController::class, 'updateYear'])->name('academic-years.update');
    Route::post('/grade-levels', [AcademicController::class, 'storeGrade'])->name('grade-levels.store');
    Route::patch('/grade-levels/{gradeLevel}', [AcademicController::class, 'updateGrade'])->name('grade-levels.update');
    Route::post('/subjects', [AcademicController::class, 'storeSubject'])->name('subjects.store');
    Route::patch('/subjects/{subject}', [AcademicController::class, 'updateSubject'])->name('subjects.update');
    Route::post('/school-classes', [AcademicController::class, 'storeClass'])->name('school-classes.store');
    Route::patch('/school-classes/{schoolClass}', [AcademicController::class, 'updateClass'])->name('school-classes.update');
    Route::patch('/school-classes/{schoolClass}/join-code', [SchoolClassJoinCodeController::class, 'update'])->name('school-classes.join-code.update');
    Route::put('/school-classes/{schoolClass}/subjects', [AcademicController::class, 'syncSubjects'])->name('school-classes.subjects');
    Route::get('/people', [PeopleController::class, 'index'])->name('people.index');
    Route::post('/teacher-profiles', [PeopleController::class, 'storeTeacher'])->name('teacher-profiles.store');
    Route::patch('/teacher-profiles/{teacherProfile}', [PeopleController::class, 'updateTeacher'])->name('teacher-profiles.update');
    Route::post('/student-profiles', [PeopleController::class, 'storeStudent'])->name('student-profiles.store');
    Route::patch('/student-profiles/{studentProfile}', [PeopleController::class, 'updateStudent'])->name('student-profiles.update');
    Route::post('/student-profiles/{studentProfile}/enrollments', [PeopleController::class, 'enroll'])->name('enrollments.store');
    Route::patch('/enrollments/{enrollment}/end', [PeopleController::class, 'end'])->name('enrollments.end');
    Route::post('/enrollments/{enrollment}/transfer', [PeopleController::class, 'transfer'])->name('enrollments.transfer');
    Route::post('/school-classes/{schoolClass}/teacher', [PeopleController::class, 'assignClass'])->name('teacher-class-assignments.store');
    Route::post('/class-subjects/{classSubject}/teacher', [PeopleController::class, 'assignSubject'])->name('teacher-class-subject-assignments.store');
    Route::get('/collaboration', [CollaborationController::class, 'index'])->name('collaboration.index');
    Route::get('/conversations', [ConversationController::class, 'index'])->name('conversations.index');
    Route::post('/conversations/groups', [ConversationController::class, 'storeGroup'])->middleware('throttle:messages-create')->name('conversations.groups.store');
    Route::get('/conversations/{conversation}', [ConversationController::class, 'show'])->name('conversations.show');
    Route::post('/conversations/{conversation}/messages', [ConversationController::class, 'send'])->middleware('throttle:messages-create')->name('conversations.messages.store');
    Route::patch('/conversations/{conversation}/messages/{message}', [ConversationMessageExperienceController::class, 'update'])->name('conversations.messages.update');
    Route::delete('/conversations/{conversation}/messages/{message}', [ConversationMessageExperienceController::class, 'destroy'])->name('conversations.messages.destroy');
    Route::post('/conversations/{conversation}/messages/{message}/reactions', [ConversationMessageExperienceController::class, 'react'])->name('conversations.messages.react');
    Route::post('/conversations/{conversation}/reads', [ConversationMessageExperienceController::class, 'read'])->name('conversations.messages.read');
    Route::get('/conversations/{conversation}/search', [ConversationMessageExperienceController::class, 'search'])->name('conversations.messages.search');
    Route::post('/conversations/{conversation}/typing', [ConversationMessageExperienceController::class, 'typing'])->middleware('throttle:30,1')->name('conversations.typing');
    Route::post('/conversations/{conversation}/messages/{message}/forward', [ConversationMessageExperienceController::class, 'forward'])->name('conversations.messages.forward');
    Route::put('/conversations/{conversation}/pin/{message}', [ConversationMessageExperienceController::class, 'pin'])->name('conversations.pin');
    Route::delete('/conversations/{conversation}/pin', [ConversationMessageExperienceController::class, 'unpin'])->name('conversations.pin.destroy');
    Route::get('/conversations/{conversation}/attachments/{attachment}', [ConversationAttachmentController::class, 'show'])->name('conversations.attachments.show');
    Route::post('/conversations/{conversation}/calls', [ConversationCallController::class, 'store'])->middleware('throttle:messages-create')->name('conversation-calls.store');
    Route::patch('/conversations/{conversation}', [ConversationController::class, 'rename'])->name('conversations.update');
    Route::post('/conversations/{conversation}/members', [ConversationController::class, 'addMembers'])->name('conversations.members.store');
    Route::delete('/conversations/{conversation}/members/{user}', [ConversationController::class, 'removeMember'])->name('conversations.members.destroy');
    Route::post('/conversations/{conversation}/leave', [ConversationController::class, 'leave'])->name('conversations.leave');
    Route::get('/conversation-calls/{call}/room', [ConversationCallController::class, 'room'])->name('conversation-calls.room');
    Route::get('/conversation-calls/active', [ConversationCallController::class, 'active'])->name('conversation-calls.active');
    Route::post('/conversation-calls/{call}/respond', [ConversationCallController::class, 'respond'])->name('conversation-calls.respond');
    Route::post('/conversation-calls/{call}/cancel', [ConversationCallController::class, 'cancel'])->name('conversation-calls.cancel');
    Route::post('/conversation-calls/{call}/leave', [ConversationCallController::class, 'leave'])->name('conversation-calls.leave');
    Route::post('/conversation-calls/{call}/token', [ConversationCallController::class, 'token'])->middleware('throttle:meeting-tokens')->name('conversation-calls.token');
    Route::post('/classes/{schoolClass}/members/{user}/chat', [ConversationController::class, 'openDirect'])->name('classes.members.chat');
    Route::get('/collaboration/classes/{schoolClass}', [CollaborationController::class, 'workspace'])->name('collaboration.classes.show');
    Route::get('/collaboration/classes/{schoolClass}/channels/{channel}', [CollaborationController::class, 'workspace'])->name('collaboration.channels.show');
    Route::get('/attendance', [AttendanceController::class, 'index'])->name('attendance.index');
    Route::get('/attendance/reports', [AttendanceController::class, 'report'])->name('attendance.reports');
    Route::get('/attendance/reports/export', [AttendanceController::class, 'export'])->name('attendance.reports.export');
    Route::get('/my-attendance', [AttendanceController::class, 'myAttendance'])->name('attendance.mine');
    Route::scopeBindings()->group(function () {
        Route::post('/school-classes/{schoolClass}/attendance', [AttendanceController::class, 'store'])->name('attendance.registers.store');
        Route::get('/school-classes/{schoolClass}/attendance/{attendanceRegister}', [AttendanceController::class, 'show'])->name('attendance.registers.show');
        Route::patch('/school-classes/{schoolClass}/attendance/{attendanceRegister}/records', [AttendanceController::class, 'bulk'])->name('attendance.records.bulk');
        Route::patch('/school-classes/{schoolClass}/attendance/{attendanceRegister}/records/{record}', [AttendanceController::class, 'update'])->name('attendance.records.update');
        Route::post('/school-classes/{schoolClass}/attendance/{attendanceRegister}/finalize', [AttendanceController::class, 'finalize'])->name('attendance.registers.finalize');
        Route::post('/school-classes/{schoolClass}/attendance/{attendanceRegister}/records/{record}/correct', [AttendanceController::class, 'correct'])->name('attendance.records.correct');
        Route::get('/school-classes/{schoolClass}/coursework', [CourseworkController::class, 'index'])->name('coursework.index');
        Route::get('/school-classes/{schoolClass}/class-subjects/{classSubject}/assignments/create', [CourseworkController::class, 'create'])->name('coursework.assignments.create');
        Route::post('/school-classes/{schoolClass}/class-subjects/{classSubject}/assignments', [CourseworkController::class, 'store'])->name('coursework.assignments.store');
        Route::get('/school-classes/{schoolClass}/class-subjects/{classSubject}/assignments/{assignment}', [CourseworkController::class, 'show'])->name('coursework.assignments.show');
        Route::get('/school-classes/{schoolClass}/class-subjects/{classSubject}/assignments/{assignment}/edit', [CourseworkController::class, 'edit'])->name('coursework.assignments.edit');
        Route::patch('/school-classes/{schoolClass}/class-subjects/{classSubject}/assignments/{assignment}', [CourseworkController::class, 'update'])->name('coursework.assignments.update');
        foreach (['publish', 'close', 'archive', 'restore'] as $ability) {
            Route::post("/school-classes/{schoolClass}/class-subjects/{classSubject}/assignments/{assignment}/{$ability}", [CourseworkController::class, 'transition'])->defaults('courseworkAbility', $ability)->name("coursework.assignments.{$ability}");
        }
        Route::put('/school-classes/{schoolClass}/class-subjects/{classSubject}/assignments/{assignment}/submission/draft', [AssignmentSubmissionController::class, 'save'])->middleware('throttle:attachments-upload')->name('coursework.submissions.save');
        Route::post('/school-classes/{schoolClass}/class-subjects/{classSubject}/assignments/{assignment}/submissions/{submission}/submit', [AssignmentSubmissionController::class, 'submit'])->name('coursework.submissions.submit');
        Route::post('/school-classes/{schoolClass}/class-subjects/{classSubject}/assignments/{assignment}/submissions/{submission}/resubmit', [AssignmentSubmissionController::class, 'resubmit'])->name('coursework.submissions.resubmit');
        Route::post('/school-classes/{schoolClass}/class-subjects/{classSubject}/assignments/{assignment}/submissions/{submission}/grades', [AssignmentGradeController::class, 'store'])->name('coursework.grades.store');
        Route::get('/school-classes/{schoolClass}/class-subjects/{classSubject}/assignments/{assignment}/submissions/{submission}/revisions/{revision}/attachments/{attachment}', [AssignmentSubmissionAttachmentController::class, 'download'])->middleware('throttle:attachments-download')->name('coursework.attachments.download');
        Route::get('/school-classes/{schoolClass}/class-subjects/{classSubject}/assignments/{assignment}/submissions/{submission}/revisions/{revision}/attachments/{attachment}/preview', [AssignmentSubmissionAttachmentController::class, 'preview'])->middleware('throttle:attachments-download')->name('coursework.attachments.preview');
        Route::delete('/school-classes/{schoolClass}/class-subjects/{classSubject}/assignments/{assignment}/submissions/{submission}/revisions/{revision}/attachments/{attachment}', [AssignmentSubmissionAttachmentController::class, 'destroy'])->name('coursework.attachments.destroy');
        Route::post('/school-classes/{schoolClass}/meeting-series', [MeetingSeriesController::class, 'store'])->name('meeting-series.store');
        Route::patch('/school-classes/{schoolClass}/meeting-series/{meetingSeries}', [MeetingSeriesController::class, 'update'])->name('meeting-series.update');
        Route::post('/school-classes/{schoolClass}/meeting-series/{meetingSeries}/split', [MeetingSeriesController::class, 'split'])->name('meeting-series.split');
        Route::post('/school-classes/{schoolClass}/meeting-series/{meetingSeries}/cancel', [MeetingSeriesController::class, 'cancel'])->name('meeting-series.cancel');
        Route::patch('/school-classes/{schoolClass}/meeting-series/{meetingSeries}/occurrences/{meeting}', [MeetingSeriesController::class, 'updateOccurrence'])->name('meeting-series.occurrences.update');
        Route::post('/school-classes/{schoolClass}/meeting-series/{meetingSeries}/occurrences/{meeting}/cancel', [MeetingSeriesController::class, 'cancelOccurrence'])->name('meeting-series.occurrences.cancel');
        Route::get('/school-classes/{schoolClass}/meetings', [MeetingController::class, 'index'])->name('meetings.index');
        Route::get('/school-classes/{schoolClass}/meetings/create', [MeetingController::class, 'create'])->name('meetings.create');
        Route::post('/school-classes/{schoolClass}/meetings', [MeetingController::class, 'store'])->name('meetings.store');
        Route::get('/school-classes/{schoolClass}/meetings/{meeting}', [MeetingController::class, 'show'])->name('meetings.show');
        Route::get('/school-classes/{schoolClass}/meetings/{meeting}/edit', [MeetingController::class, 'edit'])->name('meetings.edit');
        Route::patch('/school-classes/{schoolClass}/meetings/{meeting}', [MeetingController::class, 'update'])->name('meetings.update');
        Route::patch('/school-classes/{schoolClass}/meetings/{meeting}/cancel', [MeetingController::class, 'cancel'])->name('meetings.cancel');
        Route::post('/school-classes/{schoolClass}/meetings/{meeting}/start', [MeetingLifecycleController::class, 'start'])->name('meetings.start');
        Route::post('/school-classes/{schoolClass}/meetings/{meeting}/end', [MeetingLifecycleController::class, 'end'])->name('meetings.end');
        Route::post('/school-classes/{schoolClass}/meetings/{meeting}/reconcile', [MeetingLifecycleController::class, 'reconcile'])->middleware('throttle:meeting-lifecycle')->name('meetings.reconcile');
        Route::get('/school-classes/{schoolClass}/meetings/{meeting}/attendance', [MeetingAttendanceController::class, 'show'])->name('meetings.attendance.show');
        Route::get('/school-classes/{schoolClass}/meetings/{meeting}/attendance/export', [MeetingAttendanceController::class, 'export'])->name('meetings.attendance.export');
        Route::post('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/token', [MeetingTokenController::class, 'store'])->middleware('throttle:meeting-tokens')->name('meetings.token');
        Route::get('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/lobby', [MeetingExperienceController::class, 'lobby'])->name('meetings.lobby');
        Route::get('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/room', [MeetingExperienceController::class, 'room'])->name('meetings.room');
        Route::get('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/waiting-room', [MeetingWaitingRoomController::class, 'show'])->name('meetings.waiting-room.show');
        Route::post('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/waiting-room', [MeetingWaitingRoomController::class, 'store'])->middleware('throttle:meeting-tokens')->name('meetings.waiting-room.store');
        Route::delete('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/waiting-room', [MeetingWaitingRoomController::class, 'destroy'])->name('meetings.waiting-room.destroy');
        Route::get('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/waiting-room/requests', [MeetingJoinRequestController::class, 'index'])->name('meetings.join-requests.index');
        Route::patch('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/waiting-room/requests/{joinRequest:public_uuid}', [MeetingJoinRequestController::class, 'update'])->middleware('throttle:meeting-participant-removals')->name('meetings.join-requests.update');
        Route::get('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/participants', [MeetingParticipantController::class, 'index'])->name('meetings.participants.index');
        Route::patch('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/participants/{participant:public_uuid}/mute', [MeetingParticipantController::class, 'mute'])->middleware('throttle:meeting-participant-removals')->name('meetings.participants.mute');
        Route::delete('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/participants/{participant:public_uuid}', [MeetingParticipantController::class, 'destroy'])->middleware('throttle:meeting-participant-removals')->name('meetings.participants.destroy');
        Route::get('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/screen-share-requests', [MeetingScreenShareRequestController::class, 'index'])->name('meetings.screen-share-requests.index');
        Route::post('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/screen-share-requests', [MeetingScreenShareRequestController::class, 'store'])->middleware('throttle:meeting-screen-share-requests')->name('meetings.screen-share-requests.store');
        Route::post('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/screen-share-requests/{screenShareRequest:public_uuid}/reconcile', [MeetingScreenShareRequestController::class, 'reconcile'])->middleware('throttle:meeting-screen-share-requests')->name('meetings.screen-share-requests.reconcile');
        Route::patch('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/screen-share-requests/{screenShareRequest:public_uuid}', [MeetingScreenShareRequestController::class, 'update'])->middleware('throttle:meeting-screen-share-requests')->name('meetings.screen-share-requests.update');
        Route::delete('/collaboration/classes/{schoolClass}/meetings/{meeting:uuid}/screen-share-requests/{screenShareRequest:public_uuid}', [MeetingScreenShareRequestController::class, 'destroy'])->middleware('throttle:meeting-screen-share-requests')->name('meetings.screen-share-requests.destroy');
    });
    Route::post('/collaboration/classes/{schoolClass}/channels', [ChannelController::class, 'store'])->name('collaboration.channels.store');
    Route::patch('/collaboration/classes/{schoolClass}/channels/{channel}', [ChannelController::class, 'update'])->name('collaboration.channels.update');
    Route::patch('/collaboration/classes/{schoolClass}/channels/{channel}/archive', [ChannelController::class, 'archive'])->name('collaboration.channels.archive');
    Route::patch('/collaboration/classes/{schoolClass}/channels/{channel}/restore', [ChannelController::class, 'restore'])->name('collaboration.channels.restore');
    Route::get('/collaboration/classes/{schoolClass}/channels/{channel}/announcements/create', [AnnouncementController::class, 'create'])->name('collaboration.announcements.create');
    Route::post('/collaboration/classes/{schoolClass}/channels/{channel}/announcements', [AnnouncementController::class, 'store'])->name('collaboration.announcements.store');
    Route::get('/collaboration/classes/{schoolClass}/channels/{channel}/announcements/{announcement}/edit', [AnnouncementController::class, 'edit'])->name('collaboration.announcements.edit');
    Route::patch('/collaboration/classes/{schoolClass}/channels/{channel}/announcements/{announcement}', [AnnouncementController::class, 'update'])->name('collaboration.announcements.update');
    Route::patch('/collaboration/classes/{schoolClass}/channels/{channel}/announcements/{announcement}/schedule', [AnnouncementController::class, 'schedule'])->name('collaboration.announcements.schedule');
    Route::patch('/collaboration/classes/{schoolClass}/channels/{channel}/announcements/{announcement}/publish', [AnnouncementController::class, 'publish'])->name('collaboration.announcements.publish');
    Route::patch('/collaboration/classes/{schoolClass}/channels/{channel}/announcements/{announcement}/archive', [AnnouncementController::class, 'archive'])->name('collaboration.announcements.archive');
    Route::patch('/collaboration/classes/{schoolClass}/channels/{channel}/announcements/{announcement}/restore', [AnnouncementController::class, 'restore'])->name('collaboration.announcements.restore');
    Route::scopeBindings()->group(function () {
        Route::get('/collaboration/classes/{schoolClass}/channels/{channel}/messages', [MessageController::class, 'index'])->name('collaboration.messages.index');
        Route::post('/collaboration/classes/{schoolClass}/channels/{channel}/messages', [MessageController::class, 'store'])->middleware(['throttle:messages-create', 'throttle:attachments-upload'])->name('collaboration.messages.store');
        Route::patch('/collaboration/classes/{schoolClass}/channels/{channel}/messages/{message}', [MessageController::class, 'update'])->middleware('throttle:messages-mutate')->name('collaboration.messages.update');
        Route::patch('/collaboration/classes/{schoolClass}/channels/{channel}/messages/{message}/hide', [MessageController::class, 'hide'])->middleware('throttle:messages-mutate')->name('collaboration.messages.hide');
        Route::patch('/collaboration/classes/{schoolClass}/channels/{channel}/messages/{message}/moderate', [MessageController::class, 'moderate'])->middleware('throttle:messages-mutate')->name('collaboration.messages.moderate');
        Route::get('/collaboration/classes/{schoolClass}/channels/{channel}/messages/{message}/attachments/{attachment}', [MessageAttachmentController::class, 'download'])->middleware('throttle:attachments-download')->name('collaboration.attachments.download');
        Route::get('/collaboration/classes/{schoolClass}/channels/{channel}/messages/{message}/attachments/{attachment}/preview', [MessageAttachmentController::class, 'preview'])->middleware('throttle:attachments-download')->name('collaboration.attachments.preview');
        Route::put('/collaboration/classes/{schoolClass}/channels/{channel}/messages/{message}/reaction', [MessageReactionController::class, 'update'])->middleware('throttle:reactions')->name('collaboration.reactions.update');
        Route::delete('/collaboration/classes/{schoolClass}/channels/{channel}/messages/{message}/reaction', [MessageReactionController::class, 'destroy'])->middleware('throttle:reactions')->name('collaboration.reactions.destroy');
        Route::put('/collaboration/classes/{schoolClass}/channels/{channel}/read-state', [ChannelReadStateController::class, 'update'])->middleware('throttle:messages-read')->name('collaboration.read-state.update');
    });
});
