import React from 'react';
import {Head, Link, usePage} from '@inertiajs/react';
import Layout from '../Layouts/AuthenticatedLayout';
import EmptyState from '../Components/UI/EmptyState';
import Icon from '../Components/UI/Icon';
import SectionCard from '../Components/UI/SectionCard';
import StatCard from '../Components/UI/StatCard';
import StatusBadge from '../Components/UI/StatusBadge';
import educationHero from '../assets/edway-hero-education.svg';
import attendanceEmpty from '../assets/edway-empty-attendance.svg';
import courseworkEmpty from '../assets/edway-empty-coursework.svg';
import periodsEmpty from '../assets/edway-empty-periods.svg';

export default function Dashboard({variant = 'student', academicYear, metrics = [], classes = [], attendanceToday = {}, assignments = [], meetings = [], reportingPeriods = [], quickActions = []}) {
    const {auth} = usePage().props;
    const isAdministrator = variant === 'admin' || variant === 'super-admin';
    const dashboardSubtitle = isAdministrator ? 'Overview of BBU ONLINE LEARNING operations' : variant === 'teacher' ? 'Overview of your teaching workspace' : 'Overview of your learning workspace';
    const heroDescription = isAdministrator ? 'Manage BBU ONLINE LEARNING operations from one place.' : variant === 'teacher' ? 'Your classes, coursework, attendance, and meetings are ready.' : 'Continue learning across your BBU classes.';
    const attendanceTotal = attendanceToday.total || 0;

    return <Layout><Head title="Dashboard"/>
        <header className="mb-2"><h1 className="text-xl font-bold tracking-tight text-slate-900">Dashboard</h1><p className="mt-0.5 text-sm text-slate-500">{dashboardSubtitle}</p></header>
        <section className="bbu-dashboard-hero relative mt-3 min-h-56 overflow-hidden rounded-2xl px-6 py-5 text-white sm:px-7"><div className="absolute -left-16 top-10 h-44 w-72 rounded-full bg-white/7"/><div className="absolute -bottom-28 left-[36%] h-64 w-96 rounded-[50%] border border-white/10 bg-white/5"/><div className="absolute right-[31%] top-7 h-2 w-2 rounded-full bg-amber-300 shadow-[0_0_14px_rgba(255,211,109,.9)]"/><div className="absolute right-[46%] bottom-12 h-2 w-2 rounded-full bg-white/60"/><div className="relative grid min-h-52 items-center gap-1 md:grid-cols-[minmax(0,1.3fr)_minmax(280px,.9fr)]"><div className="max-w-xl"><p className="inline-flex items-center gap-2 text-xs font-semibold text-sky-100"><span className="inline-flex h-7 w-7 items-center justify-center rounded-lg bg-white/14 shadow-inner shadow-white/10"><Icon name="calendar" className="h-4 w-4"/></span>{academicYear?.name || 'Academic year not configured'}</p><p className="mt-3 text-[10px] font-bold tracking-[.16em] text-sky-100">BBU ONLINE LEARNING</p><h2 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Welcome back, {auth.user.name}! <span aria-hidden="true">👋</span></h2><p className="mt-2 max-w-md text-sm leading-6 text-sky-100">{heroDescription}</p><div className="mt-4 flex flex-wrap gap-2">{quickActions.map((action) => <Link key={action.url} href={action.url} className="inline-flex min-h-9 items-center gap-2 rounded-lg bg-white px-3 py-2 text-xs font-bold text-sky-800 shadow-[0_5px_12px_rgba(4,36,77,.2)] transition hover:bg-sky-50 focus:outline-none focus:ring-2 focus:ring-white"><Icon name={actionIcon(action.label)} className="h-4 w-4"/>{action.label}</Link>)}</div></div><div className="pointer-events-none relative self-end md:self-center"><div className="absolute inset-x-8 bottom-1 h-8 rounded-full bg-slate-950/25 blur-xl"/><img src={educationHero} alt="Original BBU ONLINE LEARNING education desk with books, graduation cap, lamp and plant" className="relative mx-auto -mb-5 w-full max-w-[400px] drop-shadow-[0_24px_20px_rgba(4,36,77,.35)] md:ml-auto md:max-w-[480px]"/></div></div></section>
        <section className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map((metric) => <StatCard key={metric.label} {...metric} tone={metricTone(metric.label)} action={<MetricAction action={metricAction(quickActions, metric.label)}/>}/>)}</section>
        <section className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.72fr)_minmax(310px,.9fr)]"><SectionCard icon="calendar" tone="mint" title="Attendance today" description="Registers available within your authorized classes." action={<InlineAction action={findAction(quickActions, 'Attendance')}/>}>{<><dl className="grid grid-cols-2 gap-2.5 sm:grid-cols-5"><AttendanceCount label="Present" value={attendanceToday.present} total={attendanceTotal}/><AttendanceCount label="Absent" value={attendanceToday.absent} total={attendanceTotal}/><AttendanceCount label="Late" value={attendanceToday.late} total={attendanceTotal}/><AttendanceCount label="Excused" value={attendanceToday.excused} total={attendanceTotal}/><AttendanceCount label="Total" value={attendanceTotal} total={attendanceTotal}/></dl>{attendanceTotal === 0 && <div className="mt-4 flex flex-col items-center justify-center gap-4 border-t border-indigo-50 pt-4 text-center sm:flex-row sm:text-left"><img src={attendanceEmpty} alt="" className="h-24 w-36 object-contain"/><div><p className="text-sm font-bold text-slate-800">No attendance recorded yet</p><p className="mt-1 max-w-sm text-xs leading-5 text-slate-500">Attendance summaries will appear here once a register is available for an authorized class.</p></div></div>}</>}</SectionCard><SectionCard icon="chart" tone="lavender" title="Reporting periods" description="Academic context only; results are not calculated here." action={<InlineAction action={findAction(quickActions, 'Results')}/>}>{reportingPeriods.length ? <div className="space-y-2">{reportingPeriods.map((period) => <div className="flex items-center justify-between gap-3 rounded-xl border border-indigo-50 bg-indigo-50/35 px-3 py-2.5" key={period.id}><span className="font-semibold text-slate-800">{period.name}</span><StatusBadge value={period.status}/></div>)}</div> : <IllustratedPanel asset={periodsEmpty} title="No reporting periods are configured" text="Configure reporting periods to start managing results and assessments." action={findAction(quickActions, 'Results')}/>}</SectionCard></section>
        <section className="mt-5 grid gap-4 xl:grid-cols-2"><SectionCard icon="school" tone="blue" title={variant === 'teacher' || variant === 'student' ? 'My classes' : 'Classes'} description="Only classes available to your account are listed."><div className="space-y-2">{classes.length ? classes.map((schoolClass) => <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-indigo-50 bg-slate-50/65 p-3.5 transition hover:border-indigo-100 hover:bg-indigo-50/30" key={schoolClass.id}><div className="flex min-w-0 items-center gap-3"><span className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl edway-tone-lavender text-indigo-700"><Icon name="school" className="h-5 w-5"/></span><div><p className="font-bold text-slate-900">{schoolClass.name}</p><p className="mt-0.5 text-xs text-slate-500">{schoolClass.academic_year || 'Academic year not available'}</p></div></div><div className="flex gap-3 text-xs font-bold">{schoolClass.attendance_url && <Link className="text-indigo-600 hover:text-indigo-800 focus:outline-none focus:underline" href={schoolClass.attendance_url}>Attendance</Link>}{schoolClass.coursework_url && <Link className="text-indigo-600 hover:text-indigo-800 focus:outline-none focus:underline" href={schoolClass.coursework_url}>Coursework</Link>}</div></div>) : <EmptyState text="No current classes are available for this account."/>}</div></SectionCard><SectionCard icon="clipboard" tone="coral" title="Coursework" description="Recent authorized assignments.">{assignments.length ? <div className="space-y-2">{assignments.map((assignment, index) => <div className="flex items-start justify-between gap-3 rounded-xl border border-slate-100 bg-slate-50/50 p-3.5 transition hover:border-indigo-100" key={`${assignment.title}-${index}`}><div className="min-w-0"><p className="truncate font-bold text-slate-900">{assignment.title}</p><p className="mt-1 flex flex-wrap items-center gap-x-2 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><Icon name="book" className="h-3.5 w-3.5 text-indigo-500"/>{assignment.subject}</span>{assignment.due_at && <span>Due {new Date(assignment.due_at).toLocaleDateString()}</span>}</p></div><StatusBadge value={assignment.status}/></div>)}</div> : <IllustratedPanel asset={courseworkEmpty} title="No coursework is available" text="Authorized coursework for your current class context will appear here."/>}</SectionCard></section>
        <section className="mt-5 grid gap-4 xl:grid-cols-[minmax(0,1.65fr)_minmax(300px,.9fr)]"><SectionCard icon="video" tone="blue" title="Meetings" description="Scheduled or active meetings from your authorized classes.">{meetings.length ? <div className="grid gap-2 md:grid-cols-2">{meetings.map((meeting, index) => <div className="rounded-xl border border-sky-100 bg-sky-50/35 p-3.5" key={`${meeting.title}-${index}`}><div className="flex justify-between gap-3"><p className="font-bold text-slate-900">{meeting.title}</p><StatusBadge value={meeting.status}/></div><p className="mt-2 flex items-center gap-1.5 text-xs text-slate-500"><Icon name="school" className="h-3.5 w-3.5"/>{meeting.school_class}</p><p className="mt-2 flex items-center gap-1.5 text-xs font-medium text-slate-700"><Icon name="calendar" className="h-3.5 w-3.5 text-indigo-500"/>{meeting.scheduled_start_at ? new Date(meeting.scheduled_start_at).toLocaleString() : 'Schedule not available'}</p></div>)}</div> : <EmptyState text="No scheduled or active meetings are available."/>}</SectionCard><SectionCard icon="bell" tone="amber" title="Activity" description="Private updates and authorized collaboration." action={<InlineAction action={findAction(quickActions, 'Notifications')}/>}>{findAction(quickActions, 'Notifications') ? <div className="rounded-xl border border-amber-100 bg-amber-50/50 p-3.5"><div className="flex items-center gap-3"><span className="inline-flex h-9 w-9 items-center justify-center rounded-xl bg-white text-amber-700 shadow-sm"><Icon name="bell" className="h-4 w-4"/></span><div><p className="text-sm font-bold text-slate-900">Notifications</p><p className="mt-0.5 text-xs leading-5 text-slate-500">Review activity delivered to your account.</p></div></div></div> : <EmptyState text="No activity inbox is available for this account."/>}<div className="mt-3 flex items-start gap-3 border-t border-indigo-50 pt-3"><span className="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-lg edway-tone-lavender text-indigo-700"><Icon name="messages" className="h-4 w-4"/></span><div><p className="text-sm font-bold text-slate-900">Collaboration</p><p className="mt-0.5 text-xs leading-5 text-slate-500">Continue in your authorized class spaces.</p></div></div></SectionCard></section>
    </Layout>;
}

function AttendanceCount({label, value, total}) { const numeric = value || 0; const percentage = label !== 'Total' && total > 0 ? `${Math.round((numeric / total) * 100)}%` : null; return <div className={`rounded-xl p-3 ${attendanceTone(label)}`}><div className="flex items-start justify-between gap-2"><span className="inline-flex h-7 w-7 items-center justify-center rounded-lg bg-white/75"><Icon name={attendanceIcon(label)} className="h-4 w-4"/></span>{percentage && <span className="text-[10px] font-bold text-slate-500">{percentage}</span>}</div><dt className="mt-2 text-xs font-semibold text-slate-600">{label}</dt><dd className="mt-0.5 text-xl font-bold text-slate-900">{numeric}</dd></div>; }
function IllustratedPanel({asset, title, text, action}) { return <div className="flex min-h-52 flex-col items-center justify-center px-2 py-1 text-center"><img src={asset} alt="" className="h-28 w-44 object-contain drop-shadow-sm"/><p className="mt-1.5 text-sm font-bold text-slate-800">{title}</p><p className="mt-1 max-w-[265px] text-xs leading-5 text-slate-500">{text}</p>{action && <Link href={action.url} className="mt-3 inline-flex min-h-9 items-center gap-1.5 rounded-xl bg-indigo-600 px-3.5 py-2 text-xs font-bold text-white shadow-[0_7px_14px_rgba(90,79,208,.25)] transition hover:bg-indigo-700"><Icon name={actionIcon(action.label)} className="h-3.5 w-3.5"/>View results</Link>}</div>; }
function MetricAction({action}) { return action ? <Link href={action.url} className="rounded-lg bg-white/70 px-2 py-1 text-[10px] font-bold text-indigo-600 transition hover:bg-white">View all →</Link> : null; }
function InlineAction({action}) { return action ? <Link href={action.url} className="text-xs font-bold text-indigo-600 transition hover:text-indigo-800 focus:outline-none focus:underline">View all →</Link> : null; }
function findAction(actions, label) { return actions.find((action) => action.label === label); }
function metricAction(actions, label) { return {Students: findAction(actions, 'Students')}[label] || null; }
function actionIcon(label) { return {Students: 'users', Attendance: 'calendar', Results: 'chart', Notifications: 'bell'}[label] || 'spark'; }
function metricTone(label) { return {Students: 'indigo', Teachers: 'sky', Classes: 'amber', Subjects: 'coral'}[label] || 'indigo'; }
function attendanceIcon(label) { return {Present: 'present', Absent: 'absent', Late: 'late', Excused: 'excused', Total: 'total'}[label] || 'total'; }
function attendanceTone(label) { return {Present: 'edway-tone-mint', Absent: 'edway-tone-coral', Late: 'edway-tone-amber', Excused: 'edway-tone-blue'}[label] || 'edway-tone-lavender'; }
