import React from 'react';
import {useForm} from '@inertiajs/react';
import Icon from '../UI/Icon';
import SectionCard from '../UI/SectionCard';

export default function AssignmentForm({action, method = 'post', assignment = null}) {
    const form = useForm({title: assignment?.title || '', instructions: assignment?.instructions || '', max_points: assignment?.max_points || 100, due_at: assignment?.due_at?.slice(0, 16) || '', allow_resubmission: assignment?.allow_resubmission ?? true, lifecycle_version: assignment?.lifecycle_version ?? 0});
    const submit = (event) => { event.preventDefault(); form.transform((data) => assignment?.status === 'published' ? {title: data.title, instructions: data.instructions, due_at: data.due_at, lifecycle_version: data.lifecycle_version} : data)[method](action); };
    const published = assignment?.status === 'published';
    return <form onSubmit={submit} className="space-y-6"><SectionCard icon="clipboard" tone="lavender" title="Assignment details" description="Use clear instructions so students understand the work they are submitting."><div className="grid gap-5"><Field label="Title" error={form.errors.title}><input className="field" value={form.data.title} onChange={(event) => form.setData('title', event.target.value)} required/></Field><Field label="Instructions"><textarea className="field min-h-44" value={form.data.instructions} onChange={(event) => form.setData('instructions', event.target.value)} placeholder="Describe the learning task, expected response, and any important context."/></Field></div></SectionCard><SectionCard icon="chart" tone="amber" title="Assessment settings" description={published ? 'Maximum points are preserved after publication.' : 'Set the assessment value and due-date context.'}><div className="grid gap-5 md:grid-cols-2"><Field label="Maximum points" error={form.errors.max_points}><input className="field" type="number" min="0.01" step="0.01" disabled={published} value={form.data.max_points} onChange={(event) => form.setData('max_points', event.target.value)}/></Field><Field label="Due date"><input className="field" type="datetime-local" value={form.data.due_at} onChange={(event) => form.setData('due_at', event.target.value)}/></Field></div>{!published && <label className="mt-5 flex items-start gap-3 rounded-xl border border-indigo-100 bg-indigo-50/50 p-4 text-sm text-slate-700"><input className="mt-0.5 h-4 w-4 rounded border-indigo-300 text-indigo-600 focus:ring-indigo-500" type="checkbox" checked={form.data.allow_resubmission} onChange={(event) => form.setData('allow_resubmission', event.target.checked)}/><span><span className="font-bold text-slate-800">Allow resubmission</span><span className="mt-1 block leading-6 text-slate-500">Students may create a new submission revision only when the existing assignment rules permit it.</span></span></label>}</SectionCard><div className="flex flex-wrap items-center gap-3"><button className="btn" disabled={form.processing}><Icon name="clipboard" className="mr-2 h-4 w-4"/>{form.processing ? 'Saving…' : 'Save assignment'}</button>{published && <span className="text-sm text-slate-500">Published assignment points remain immutable.</span>}</div></form>;
}

function Field({label, error, children}) { return <label className="text-sm font-semibold text-slate-700"><span className="mb-1.5 block">{label}</span>{children}{error && <p className="mt-1.5 text-sm font-medium text-rose-700">{error}</p>}</label>; }
