import React from 'react';
import {Head, Link} from '@inertiajs/react';
import Layout from '../../../Layouts/AuthenticatedLayout';
import Icon from '../../../Components/UI/Icon';
import AssignmentForm from '../../../Components/Coursework/AssignmentForm';

export default function Create({schoolClass, classSubject}) { return <Layout><Head title="Create assignment"/><AssignmentHeader schoolClass={schoolClass} classSubject={classSubject} eyebrow="Coursework authoring" title="New assignment"/><AssignmentForm action={`/school-classes/${schoolClass.id}/class-subjects/${classSubject.id}/assignments`}/></Layout>; }

export function AssignmentHeader({schoolClass, classSubject, eyebrow, title, backHref = null}) { return <><Link className="inline-flex items-center gap-1.5 text-sm font-bold text-indigo-600 transition hover:text-indigo-800 focus:outline-none focus:underline" href={backHref || `/school-classes/${schoolClass.id}/coursework`}>← {backHref ? 'Assignment' : 'Coursework'}</Link><header className="mt-4 mb-6 rounded-3xl border border-indigo-100 bg-gradient-to-br from-white via-indigo-50/55 to-violet-50 px-6 py-6 shadow-sm sm:px-8"><div className="flex items-start gap-4"><span className="inline-flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-indigo-600 text-white shadow-lg shadow-indigo-200"><Icon name="clipboard" className="h-6 w-6"/></span><div><p className="text-sm font-semibold text-indigo-600">{eyebrow}</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">{title}</h1><p className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-sm leading-6 text-slate-600"><span>{schoolClass.name} {schoolClass.section}</span><span className="hidden text-indigo-300 sm:inline">•</span><span className="inline-flex items-center gap-1.5"><Icon name="book" className="h-4 w-4 text-indigo-500"/>{classSubject.name}</span></p></div></div></header></>; }
