import React, {useEffect, useState} from 'react';
import {Head, Link, router, useForm, usePage} from '@inertiajs/react';
import Layout from '../../Layouts/AuthenticatedLayout';
import Icon from '../../Components/UI/Icon';
import UserAvatar from '../../Components/UI/UserAvatar';
import useConversationMessages from '../../Hooks/useConversationMessages';
import {echo} from '../../realtime/echo';

export default function Conversations({conversations = [], selectedConversation = null, eligibleUsers = []}) {
    const user = usePage().props.auth.user;
    const [showGroupForm, setShowGroupForm] = useState(false);
    return <Layout><Head title="Chats"/><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[20rem_minmax(0,1fr)]"><aside className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-sky-700">Private collaboration</p><h1 className="mt-1 text-xl font-bold text-slate-900">Chats</h1></div><button onClick={() => setShowGroupForm(value => !value)} className="inline-flex h-10 items-center gap-2 rounded-xl bg-sky-800 px-3 text-sm font-bold text-white hover:bg-sky-900"><Icon name="plus" className="h-4 w-4"/>Group</button></div>{showGroupForm && <GroupForm users={eligibleUsers} onDone={() => setShowGroupForm(false)}/>}<ConversationList conversations={conversations}/></aside><main className="min-w-0 rounded-3xl border border-slate-200 bg-white shadow-sm">{selectedConversation ? <ConversationRoom conversation={selectedConversation} currentUser={user} eligibleUsers={eligibleUsers}/> : <EmptyState/>}</main></div></Layout>;
}

function ConversationList({conversations}) { const direct = conversations.filter(item => item.type === 'direct'); const groups = conversations.filter(item => item.type === 'group'); return <div className="mt-5 space-y-5"> <List title="Direct chats" items={direct}/><List title="Groups" items={groups}/></div>; }
function List({title, items}) { return <section><h2 className="px-1 text-xs font-bold uppercase tracking-wide text-slate-400">{title}</h2><div className="mt-2 space-y-1">{items.length ? items.map(item => <Link key={item.uuid} href={item.url} className="flex min-w-0 items-center gap-3 rounded-2xl px-2.5 py-2.5 hover:bg-sky-50"><Avatar item={item}/><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-800">{item.name}</p><p className="truncate text-xs text-slate-500">{item.latest_message?.body || 'No messages yet'}</p></div></Link>) : <p className="px-2 py-3 text-sm text-slate-500">No {title.toLowerCase()} yet.</p>}</div></section>; }
function Avatar({item}) { return item.type === 'direct' ? <UserAvatar name={item.name} avatarUrl={item.avatar_url} size="md"/> : <span className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-sky-100 text-sm font-bold text-sky-800">{item.name?.split(/\s+/).map(word => word[0]).join('').slice(0, 2).toUpperCase()}</span>; }
function EmptyState() { return <div className="flex min-h-[34rem] flex-col items-center justify-center px-6 text-center"><span className="inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-sky-100 text-sky-800"><Icon name="messages" className="h-7 w-7"/></span><h2 className="mt-4 text-xl font-bold text-slate-900">Choose a conversation</h2><p className="mt-2 max-w-sm text-sm leading-6 text-slate-600">Private chats and groups are visible only to their active members.</p></div>; }
function ConversationRoom({conversation, currentUser, eligibleUsers}) {
    const {messages, send} = useConversationMessages({conversation, currentUser, initialMessages: conversation.messages || []});
    const [body, setBody] = useState(''); const [error, setError] = useState(''); const [sending, setSending] = useState(false); const [calling, setCalling] = useState(false); const [outgoingCall, setOutgoingCall] = useState(null);
    useEffect(() => {
        if (!echo || !outgoingCall) return undefined;
        const channelName = `conversation-call.${outgoingCall.uuid}`;
        const channel = echo.private(channelName)
            .listen('.conversation.call.accepted', () => router.visit(`/conversation-calls/${outgoingCall.uuid}/room`))
            .listen('.conversation.call.declined', () => { setOutgoingCall(null); setCalling(false); setError('The call was declined.'); })
            .listen('.conversation.call.cancelled', () => { setOutgoingCall(null); setCalling(false); setError('The call was cancelled.'); });
        return () => echo.leave(channelName);
    }, [outgoingCall]);
    const submit = async event => { event.preventDefault(); if (!body.trim()) return; setSending(true); setError(''); try { await send(body.trim()); setBody(''); } catch (e) { setError(e.message); } finally { setSending(false); } };
    const startCall = async type => { setCalling(true); setError(''); try { const response = await fetch(`/conversations/${conversation.uuid}/calls`, {method: 'POST', headers: {'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.content, Accept: 'application/json', 'Content-Type': 'application/json'}, body: JSON.stringify({type})}); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Unable to start call.'); if (data.call.status === 'ringing') { setOutgoingCall(data.call); return; } router.visit(data.room_url); } catch (e) { setError(e.message); setCalling(false); } };
    const cancelOutgoingCall = async () => { if (!outgoingCall) return; try { await fetch(`/conversation-calls/${outgoingCall.uuid}/cancel`, {method: 'POST', headers: {'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.content, Accept: 'application/json'}}); } finally { setOutgoingCall(null); setCalling(false); } };
    return <div className="flex min-h-[34rem] flex-col"><header className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div className="flex min-w-0 items-center gap-3"><Avatar item={conversation}/><div className="min-w-0"><h2 className="truncate font-bold text-slate-900">{conversation.name}</h2><p className="text-xs text-slate-500">{conversation.type === 'group' ? `${conversation.members.length} active members` : 'Private chat'}</p></div></div><div className="flex items-center gap-2"><button disabled={calling} onClick={() => startCall('audio')} className="rounded-lg bg-sky-50 p-2 text-sky-800" aria-label="Start audio call"><Icon name="mic" className="h-4 w-4"/></button><button disabled={calling} onClick={() => startCall('video')} className="rounded-lg bg-sky-800 p-2 text-white" aria-label="Start video call"><Icon name="video" className="h-4 w-4"/></button>{conversation.type === 'group' && <GroupActions conversation={conversation}/>}</div></header>{outgoingCall && <div role="status" className="flex items-center justify-between gap-3 border-b border-sky-100 bg-sky-50 px-5 py-3 text-sm text-sky-900"><span>Calling {conversation.name}…</span><button onClick={cancelOutgoingCall} className="rounded-lg border border-sky-200 px-3 py-1.5 font-bold">Cancel</button></div>}{conversation.type === 'group' && <GroupManagement conversation={conversation} eligibleUsers={eligibleUsers}/>}<div className="flex-1 space-y-4 overflow-y-auto bg-slate-50/60 p-5">{conversation.calls?.length > 0 && <CallHistory calls={conversation.calls}/>} {messages.length ? messages.map(message => <article key={message.id} className={`flex gap-2.5 ${String(message.sender.id) === String(currentUser.id) ? 'justify-end' : ''}`}><UserAvatar name={message.sender.name} avatarUrl={message.sender.avatar_url} size="sm"/><div className={`max-w-[80%] rounded-2xl px-3.5 py-2.5 text-sm shadow-sm ${String(message.sender.id) === String(currentUser.id) ? 'bg-sky-800 text-white' : 'bg-white text-slate-800'}`}><p className="text-xs font-bold opacity-75">{message.sender.name}</p><p className="mt-1 whitespace-pre-wrap">{message.body}</p></div></article>) : !conversation.calls?.length && <p className="pt-16 text-center text-sm text-slate-500">No messages yet. Start the conversation.</p>}</div><form onSubmit={submit} className="border-t border-slate-100 p-4"><label className="sr-only" htmlFor="conversation-body">Message</label><div className="flex gap-2"><textarea id="conversation-body" value={body} onChange={event => setBody(event.target.value)} maxLength="4000" rows="2" placeholder="Write a private message…" className="field min-h-11 flex-1 resize-none"/><button disabled={sending || !body.trim()} className="rounded-xl bg-sky-800 px-4 text-sm font-bold text-white hover:bg-sky-900 disabled:opacity-50">Send</button></div>{error && <p role="alert" className="mt-2 text-sm text-rose-700">{error}</p>}</form></div>;
}
function CallHistory({calls}) { return <section aria-label="Call history" className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Recent calls</p><div className="mt-2 space-y-2">{calls.map(call => <div key={call.uuid} className="flex items-center gap-3 rounded-xl bg-slate-50 px-3 py-2"><span className="inline-flex h-8 w-8 items-center justify-center rounded-lg bg-sky-100 text-sky-800"><Icon name={call.type === 'video' ? 'video' : 'mic'} className="h-4 w-4"/></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-800">{call.missed ? `Missed ${call.type} call` : `${call.type === 'video' ? 'Video' : 'Audio'} call · ${call.status}`}</p><p className="text-xs text-slate-500">{call.duration_seconds !== null ? `${Math.floor(call.duration_seconds / 60)}m ${call.duration_seconds % 60}s` : call.ended_at ? 'No media duration' : 'In progress'}</p></div></div>)}</div></section>; }
function GroupForm({users, onDone}) { const form = useForm({name: '', member_ids: []}); const toggle = id => form.setData('member_ids', form.data.member_ids.includes(id) ? form.data.member_ids.filter(value => value !== id) : [...form.data.member_ids, id]); return <form onSubmit={e => { e.preventDefault(); form.post('/conversations/groups', {onSuccess: onDone}); }} className="mt-4 rounded-2xl bg-sky-50 p-3"><input className="field" value={form.data.name} onChange={e => form.setData('name', e.target.value)} placeholder="Group name" maxLength="120"/><div className="mt-2 max-h-40 space-y-1 overflow-y-auto">{users.map(user => <label key={user.id} className="flex items-center gap-2 rounded-lg px-1 py-1 text-sm"><input type="checkbox" checked={form.data.member_ids.includes(user.id)} onChange={() => toggle(user.id)}/>{user.name}</label>)}</div><button disabled={form.processing} className="mt-3 w-full rounded-lg bg-sky-800 px-3 py-2 text-sm font-bold text-white">Create group</button></form>; }
function GroupActions({conversation}) { return <button onClick={() => router.post(`/conversations/${conversation.uuid}/leave`)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-bold text-slate-600">Leave</button>; }
function GroupManagement({conversation, eligibleUsers}) { const [open, setOpen] = useState(false); const rename = useForm({name: conversation.name}); const add = useForm({member_ids: []}); const memberIds = new Set(conversation.members.map(member => member.id)); const available = eligibleUsers.filter(user => !memberIds.has(user.id)); if (!conversation.can_manage) return null; return <section className="border-b border-slate-100 bg-sky-50/50 px-5 py-3"><button onClick={() => setOpen(value => !value)} className="text-sm font-bold text-sky-800">{open ? 'Hide group controls' : 'Manage group'}</button>{open && <div className="mt-3 grid gap-3 md:grid-cols-2"><form onSubmit={e => { e.preventDefault(); rename.patch(`/conversations/${conversation.uuid}`); }} className="flex gap-2"><input className="field min-w-0 flex-1" aria-label="Group name" value={rename.data.name} onChange={e => rename.setData('name', e.target.value)}/><button className="rounded-lg bg-sky-800 px-3 text-sm font-bold text-white">Rename</button></form><form onSubmit={e => { e.preventDefault(); add.post(`/conversations/${conversation.uuid}/members`); }} className="flex gap-2"><select className="field min-w-0 flex-1" value={add.data.member_ids[0] || ''} onChange={e => add.setData('member_ids', e.target.value ? [Number(e.target.value)] : [])}><option value="">Add eligible member…</option>{available.map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select><button disabled={!add.data.member_ids.length} className="rounded-lg bg-sky-800 px-3 text-sm font-bold text-white disabled:opacity-50">Add</button></form><div className="rounded-xl border border-sky-100 bg-white p-3 md:col-span-2"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Active members</p><div className="mt-2 space-y-2">{conversation.members.map(member => <div key={member.id} className="flex items-center gap-2 text-sm"><UserAvatar name={member.name} avatarUrl={member.avatar_url} size="sm"/><span className="min-w-0 flex-1 truncate font-medium text-slate-700">{member.name}</span><span className="text-xs text-slate-500">{member.role}</span>{member.role !== 'manager' && <button onClick={() => router.delete(`/conversations/${conversation.uuid}/members/${member.id}`)} className="text-xs font-bold text-rose-700">Remove</button>}</div>)}</div></div></div>}</section>; }
