import React, {useCallback, useEffect, useMemo, useRef, useState} from 'react';
import {Head, router, useForm, usePage} from '@inertiajs/react';
import Layout from '../../Layouts/AuthenticatedLayout';
import Icon from '../../Components/UI/Icon';
import UserAvatar from '../../Components/UI/UserAvatar';
import ConversationSidebar from '../../Components/Conversations/ConversationSidebar';
import ConversationHeader from '../../Components/Conversations/ConversationHeader';
import MessageBubble from '../../Components/Conversations/MessageBubble';
import ChatComposer from '../../Components/Conversations/ChatComposer';
import ConversationSearch from '../../Components/Conversations/ConversationSearch';
import ForwardMessageDialog from '../../Components/Conversations/ForwardMessageDialog';
import PinnedMessageBar from '../../Components/Conversations/PinnedMessageBar';
import TypingIndicator from '../../Components/Conversations/TypingIndicator';
import useConversationMessages from '../../Hooks/useConversationMessages';
import {echo} from '../../realtime/echo';

const csrf = () => document.querySelector('meta[name="csrf-token"]')?.content;
const dayLabel = date => { const value = new Date(date); const today = new Date(); const yesterday = new Date(); yesterday.setDate(today.getDate() - 1); if (value.toDateString() === today.toDateString()) return 'Today'; if (value.toDateString() === yesterday.toDateString()) return 'Yesterday'; return new Intl.DateTimeFormat(undefined, {month: 'short', day: 'numeric'}).format(value); };

export default function Conversations({conversations = [], selectedConversation = null, eligibleUsers = []}) {
    const [showGroupForm, setShowGroupForm] = useState(false);
    const currentUser = usePage().props.auth.user;
    return <Layout><Head title="Chats"/><div className="mx-auto max-w-7xl"><div className="grid gap-5 lg:grid-cols-[20rem_minmax(0,1fr)]"><div className={selectedConversation ? 'hidden lg:block' : ''}><ConversationSidebar conversations={conversations} selectedUuid={selectedConversation?.uuid} onCreateGroup={() => setShowGroupForm(value => !value)}/>{showGroupForm && <GroupForm users={eligibleUsers} onDone={() => setShowGroupForm(false)}/>}</div><main className={`relative min-w-0 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm ${selectedConversation ? '' : 'hidden lg:block'}`}>{selectedConversation ? <ConversationRoom conversation={selectedConversation} currentUser={currentUser} conversations={conversations} eligibleUsers={eligibleUsers}/> : <EmptyState/>}</main></div></div></Layout>;
}

function EmptyState() { return <div className="flex min-h-[38rem] flex-col items-center justify-center px-6 text-center"><span className="inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-100 text-blue-800"><Icon name="messages" className="h-7 w-7"/></span><h2 className="mt-4 text-xl font-bold text-slate-900">Choose a conversation</h2><p className="mt-2 max-w-sm text-sm leading-6 text-slate-600">Private chats and groups are visible only to their active members.</p></div>; }

function ConversationRoom({conversation, currentUser, conversations, eligibleUsers}) {
    const {messages, setMessages, send, request, update, typingUsers, pinnedMessageId, setPinnedMessageId} = useConversationMessages({conversation, currentUser, initialMessages: conversation.messages || []});
    const [body, setBody] = useState(''); const [attachments, setAttachments] = useState([]); const [reply, setReply] = useState(null); const [editing, setEditing] = useState(null); const [forwarding, setForwarding] = useState(null); const [searchOpen, setSearchOpen] = useState(false); const [infoOpen, setInfoOpen] = useState(false); const [error, setError] = useState(''); const [sending, setSending] = useState(false); const [calling, setCalling] = useState(false); const [outgoingCall, setOutgoingCall] = useState(null); const [newMessages, setNewMessages] = useState(0);
    const historyRef = useRef(null); const atBottom = useRef(true); const typingTimer = useRef(null); const sentTyping = useRef(false); const messageRefs = useRef({});
    const pinned = messages.find(message => String(message.id) === String(pinnedMessageId));
    const canPin = conversation.type === 'direct' || conversation.can_manage;
    const media = useMemo(() => messages.flatMap(message => (message.attachments || []).map(attachment => ({...attachment, message}))), [messages]);
    const receivedIds = messages.filter(message => String(message.sender.id) !== String(currentUser.id) && !message.deleted).slice(-50).map(message => message.id);

    const scrollLatest = useCallback(() => { const node = historyRef.current; if (!node) return; node.scrollTo({top: node.scrollHeight, behavior: 'smooth'}); setNewMessages(0); }, []);
    const focusMessage = useCallback(id => { const target = messageRefs.current[id]; if (!target) return; target.scrollIntoView({behavior: 'smooth', block: 'center'}); target.classList.add('ring-2', 'ring-blue-300'); window.setTimeout(() => target.classList.remove('ring-2', 'ring-blue-300'), 1200); }, []);
    useEffect(() => { window.setTimeout(() => scrollLatest(), 0); }, [conversation.uuid]);
    useEffect(() => { if (atBottom.current) scrollLatest(); else setNewMessages(value => value + 1); }, [messages.length, scrollLatest]);
    useEffect(() => { if (!receivedIds.length) return; request(`/conversations/${conversation.uuid}/reads`, {method: 'POST', body: JSON.stringify({message_ids: receivedIds})}).catch(() => {}); }, [conversation.uuid, receivedIds.join(',')]);
    useEffect(() => () => { if (sentTyping.current) request(`/conversations/${conversation.uuid}/typing`, {method: 'POST', body: JSON.stringify({typing: false})}).catch(() => {}); window.clearTimeout(typingTimer.current); }, [conversation.uuid, request]);
    useEffect(() => { if (!echo || !outgoingCall) return undefined; const name = `conversation-call.${outgoingCall.uuid}`; const channel = echo.private(name).listen('.conversation.call.accepted', () => router.visit(`/conversation-calls/${outgoingCall.uuid}/room`)).listen('.conversation.call.declined', () => { setOutgoingCall(null); setCalling(false); setError('The call was declined.'); }).listen('.conversation.call.cancelled', () => { setOutgoingCall(null); setCalling(false); setError('The call was cancelled.'); }); return () => echo.leave(name); }, [outgoingCall]);
    const sendTyping = () => { if (!sentTyping.current) { sentTyping.current = true; request(`/conversations/${conversation.uuid}/typing`, {method: 'POST', body: JSON.stringify({typing: true})}).catch(() => {}); } window.clearTimeout(typingTimer.current); typingTimer.current = window.setTimeout(() => { if (!sentTyping.current) return; sentTyping.current = false; request(`/conversations/${conversation.uuid}/typing`, {method: 'POST', body: JSON.stringify({typing: false})}).catch(() => {}); }, 2500); };
    const clearMode = () => { setReply(null); setEditing(null); setBody(''); };
    const submit = async event => { event.preventDefault(); if (!body.trim() && !attachments.length) return; setSending(true); setError(''); try { if (editing) { const data = await request(`/conversations/${conversation.uuid}/messages/${editing.id}`, {method: 'PATCH', body: JSON.stringify({body: body.trim()})}); update(editing.id, message => ({...message, ...data.message, edited: true})); } else await send(body.trim(), attachments, reply?.id); clearMode(); setAttachments([]); if (sentTyping.current) { sentTyping.current = false; request(`/conversations/${conversation.uuid}/typing`, {method: 'POST', body: JSON.stringify({typing: false})}).catch(() => {}); } } catch (exception) { setError(exception.message); } finally { setSending(false); } };
    const startCall = async type => { setCalling(true); setError(''); try { const data = await request(`/conversations/${conversation.uuid}/calls`, {method: 'POST', body: JSON.stringify({type})}); if (data.call.status === 'ringing') setOutgoingCall(data.call); else router.visit(data.room_url); } catch (exception) { setError(exception.message); setCalling(false); } };
    const cancelOutgoingCall = async () => { if (!outgoingCall) return; try { await request(`/conversation-calls/${outgoingCall.uuid}/cancel`, {method: 'POST'}); } finally { setOutgoingCall(null); setCalling(false); } };
    const handleAction = async (action, payload) => { const message = payload?.message || payload; if (action === 'focus') return focusMessage(payload.id); if (action === 'reply') { setReply(message); setEditing(null); return; } if (action === 'edit') { setEditing(message); setReply(null); setBody(message.body || ''); return; } if (action === 'forward') { setForwarding(message); return; } if (action === 'copy') { await navigator.clipboard?.writeText(message.body || ''); return; } if (action === 'delete') { if (!window.confirm('Delete this message?')) return; const data = await request(`/conversations/${conversation.uuid}/messages/${message.id}`, {method: 'DELETE'}); update(message.id, current => ({...current, ...data.message, body: null, attachments: [], deleted: true})); return; } if (action === 'react') return; if (action === 'reactEmoji') { const data = await request(`/conversations/${conversation.uuid}/messages/${payload.message.id}/reactions`, {method: 'POST', body: JSON.stringify({emoji: payload.emoji})}); update(payload.message.id, current => ({...current, reactions: data.reactions || {}})); return; } if (action === 'pin') { const data = await request(`/conversations/${conversation.uuid}/pin/${message.id}`, {method: 'PUT'}); setPinnedMessageId(data.pinned_message_id); return; } if (action === 'unpin') { await request(`/conversations/${conversation.uuid}/pin`, {method: 'DELETE'}); setPinnedMessageId(null); } };
    const forward = async destination => { await request(`/conversations/${conversation.uuid}/messages/${forwarding.id}/forward`, {method: 'POST', body: JSON.stringify({destination_conversation: destination})}); };
    const dateMessages = messages.map((message, index) => ({message, separator: index === 0 || new Date(messages[index - 1].created_at).toDateString() !== new Date(message.created_at).toDateString()}));
    return <div className="flex min-h-[calc(100vh-11rem)] flex-col lg:min-h-[42rem]"><ConversationHeader conversation={conversation} calling={calling} onCall={startCall} onSearch={() => setSearchOpen(true)} onInfo={() => setInfoOpen(value => !value)} onBack={() => router.visit('/conversations')}/>{searchOpen && <ConversationSearch conversation={conversation} onClose={() => setSearchOpen(false)} onSelect={id => { setSearchOpen(false); focusMessage(id); }}/>}<PinnedMessageBar message={pinned} onFocus={focusMessage}/>{outgoingCall && <div role="status" className="flex items-center justify-between gap-3 border-b border-blue-100 bg-blue-50 px-5 py-3 text-sm text-blue-900"><span>Calling {conversation.name}…</span><button type="button" onClick={cancelOutgoingCall} className="rounded-lg border border-blue-200 px-3 py-1.5 font-bold">Cancel</button></div>}{conversation.type === 'group' && <GroupManagement conversation={conversation} eligibleUsers={eligibleUsers}/>}<div ref={historyRef} onScroll={event => { const node = event.currentTarget; atBottom.current = node.scrollHeight - node.scrollTop - node.clientHeight < 80; }} className="relative flex-1 space-y-3 overflow-y-auto bg-slate-50/70 p-4 sm:p-5">{conversation.calls?.length > 0 && <CallHistory calls={conversation.calls}/>} {dateMessages.map(({message, separator}) => <React.Fragment key={message.id}>{separator && <p className="sticky top-0 z-10 mx-auto w-fit rounded-full bg-white/90 px-3 py-1 text-xs font-bold text-slate-500 shadow-sm">{dayLabel(message.created_at)}</p>}<MessageBubble message={message} currentUser={currentUser} isGroup={conversation.type === 'group'} canPin={canPin} onAction={handleAction} messageRef={node => { messageRefs.current[message.id] = node; }}/></React.Fragment>)}{!messages.length && !conversation.calls?.length && <p className="pt-16 text-center text-sm text-slate-500">No messages yet. Start the conversation.</p>}{newMessages > 0 && <button type="button" onClick={scrollLatest} className="sticky bottom-2 mx-auto flex items-center gap-1 rounded-full bg-blue-800 px-3 py-2 text-xs font-bold text-white shadow-lg"><Icon name="arrow-right" className="h-3.5 w-3.5 rotate-90"/>New messages</button>}</div><TypingIndicator users={typingUsers}/><div className="border-t border-slate-100"><ChatComposer body={body} onBodyChange={setBody} attachments={attachments} onAttachmentsChange={setAttachments} onSubmit={submit} sending={sending} reply={reply} editing={editing} onCancelMode={clearMode} onTyping={sendTyping}/>{error && <p role="alert" className="px-4 pb-3 text-sm text-rose-700">{error}</p>}</div>{infoOpen && <ConversationInfoPanel media={media} onClose={() => setInfoOpen(false)}/>} {forwarding && <ForwardMessageDialog conversations={conversations.filter(item => item.uuid !== conversation.uuid)} message={forwarding} onClose={() => setForwarding(null)} onForward={forward}/>}</div>;
}

function ConversationInfoPanel({media, onClose}) { return <aside role="dialog" aria-label="Conversation media and files" className="absolute inset-y-0 right-0 z-20 flex w-full max-w-sm flex-col border-l border-slate-200 bg-white shadow-xl"><div className="flex items-center justify-between border-b border-slate-100 p-4"><h3 className="font-bold text-slate-900">Media & files</h3><button type="button" onClick={onClose} aria-label="Close conversation information" className="rounded-lg p-1 text-slate-500 hover:bg-slate-100"><Icon name="x" className="h-5 w-5"/></button></div><div className="flex-1 space-y-5 overflow-y-auto p-4"><PanelSection title="Media" items={media.filter(item => ['image', 'video'].includes(item.type))}/><PanelSection title="Files" items={media.filter(item => !['image', 'video', 'voice'].includes(item.type))}/><PanelSection title="Voice" items={media.filter(item => item.type === 'voice')}/></div></aside>; }
function PanelSection({title, items}) { return <section><h4 className="text-xs font-bold uppercase tracking-wide text-slate-400">{title}</h4>{items.length ? <div className="mt-2 space-y-2">{items.map(item => <a key={item.uuid} href={item.url} className="flex min-w-0 items-center gap-2 rounded-xl bg-slate-50 p-2 text-sm text-blue-800 hover:bg-blue-50"><Icon name={item.type === 'voice' ? 'mic' : item.type === 'video' ? 'video' : 'book'} className="h-4 w-4 shrink-0"/><span className="truncate">{item.name}</span></a>)}</div> : <p className="mt-2 text-sm text-slate-500">No {title.toLowerCase()} yet.</p>}</section>; }
function CallHistory({calls}) { return <section className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Recent calls</p>{calls.map(call => <div key={call.uuid} className="mt-2 flex items-center gap-3 rounded-xl bg-slate-50 px-3 py-2"><Icon name={call.type === 'video' ? 'video' : 'phone'} className="h-4 w-4 text-blue-800"/><p className="text-sm font-medium text-slate-700">{call.missed ? `Missed ${call.type} call` : `${call.type === 'video' ? 'Video' : 'Audio'} call · ${call.status}`}</p></div>)}</section>; }
function GroupForm({users, onDone}) { const form = useForm({name: '', member_ids: []}); const toggle = id => form.setData('member_ids', form.data.member_ids.includes(id) ? form.data.member_ids.filter(value => value !== id) : [...form.data.member_ids, id]); return <form onSubmit={event => { event.preventDefault(); form.post('/conversations/groups', {onSuccess: onDone}); }} className="mt-4 rounded-2xl border border-blue-100 bg-blue-50 p-3"><input className="field w-full" value={form.data.name} onChange={event => form.setData('name', event.target.value)} placeholder="Group name" maxLength="120"/><div className="mt-2 max-h-40 space-y-1 overflow-y-auto">{users.map(user => <label key={user.id} className="flex items-center gap-2 rounded-lg px-1 py-1 text-sm"><input type="checkbox" checked={form.data.member_ids.includes(user.id)} onChange={() => toggle(user.id)}/>{user.name}</label>)}</div><button disabled={form.processing} className="mt-3 w-full rounded-lg bg-blue-800 px-3 py-2 text-sm font-bold text-white">Create group</button></form>; }
function GroupManagement({conversation, eligibleUsers}) { const [open, setOpen] = useState(false); const rename = useForm({name: conversation.name}); const add = useForm({member_ids: []}); const memberIds = new Set(conversation.members.map(member => member.id)); const available = eligibleUsers.filter(user => !memberIds.has(user.id)); if (!conversation.can_manage) return null; return <section className="border-b border-slate-100 bg-blue-50/50 px-5 py-3"><button type="button" onClick={() => setOpen(value => !value)} className="text-sm font-bold text-blue-800">{open ? 'Hide group controls' : 'Manage group'}</button>{open && <div className="mt-3 grid gap-3 md:grid-cols-2"><form onSubmit={event => { event.preventDefault(); rename.patch(`/conversations/${conversation.uuid}`); }} className="flex gap-2"><input className="field min-w-0 flex-1" aria-label="Group name" value={rename.data.name} onChange={event => rename.setData('name', event.target.value)}/><button className="rounded-lg bg-blue-800 px-3 text-sm font-bold text-white">Rename</button></form><form onSubmit={event => { event.preventDefault(); add.post(`/conversations/${conversation.uuid}/members`); }} className="flex gap-2"><select className="field min-w-0 flex-1" value={add.data.member_ids[0] || ''} onChange={event => add.setData('member_ids', event.target.value ? [Number(event.target.value)] : [])}><option value="">Add eligible member…</option>{available.map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select><button disabled={!add.data.member_ids.length} className="rounded-lg bg-blue-800 px-3 text-sm font-bold text-white disabled:opacity-50">Add</button></form></div>}</section>; }
