import React from 'react';
import {Link} from '@inertiajs/react';
import MeetingSchedule from './MeetingSchedule';
import MeetingStatusBadge from './MeetingStatusBadge';
import Icon from '../UI/Icon';

export default function MeetingCard({schoolClass, meeting}) {
    return <article className={`edway-card relative overflow-hidden p-5 transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md ${meeting.status === 'active' ? 'border-emerald-200' : ''}`}><span className={`absolute right-0 top-0 h-20 w-20 -translate-y-8 translate-x-8 rounded-full ${meeting.status === 'active' ? 'bg-emerald-100/60' : 'bg-indigo-100/45'}`}/><div className="relative flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-3"><span className={`inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${meeting.status === 'active' ? 'edway-tone-mint text-emerald-700' : 'edway-tone-lavender text-indigo-700'}`}><Icon name="video" className="h-5 w-5"/></span><div><h2 className="font-bold text-slate-900"><Link className="hover:text-indigo-600" href={`/school-classes/${schoolClass.id}/meetings/${meeting.uuid}`}>{meeting.title}</Link></h2><p className="mt-1 flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500"><span>{meeting.class_subject?.name || 'General class meeting'}</span><span>•</span><span>Host: {meeting.host?.name || 'Unassigned'}</span></p></div></div><MeetingStatusBadge status={meeting.status}/></div><div className="relative mt-4 rounded-xl border border-indigo-50 bg-slate-50/65 p-3"><MeetingSchedule start={meeting.scheduled_start_at} end={meeting.scheduled_end_at}/></div><div className="relative mt-4 flex flex-wrap items-center gap-3"><Link className="text-sm font-bold text-indigo-600 hover:text-indigo-800 focus:outline-none focus:underline" href={`/school-classes/${schoolClass.id}/meetings/${meeting.uuid}`}>View meeting</Link>{meeting.can_join && <Link className="inline-flex items-center gap-1.5 rounded-xl edway-tone-mint px-3 py-2 text-sm font-bold text-emerald-800 transition hover:bg-emerald-100" href={`/collaboration/classes/${schoolClass.id}/meetings/${meeting.uuid}/lobby`}><Icon name="video" className="h-4 w-4"/>Join meeting</Link>}</div></article>;
}
