import React, {useState} from 'react';
import {Head, router} from '@inertiajs/react';
import Layout from '../../Layouts/AuthenticatedLayout';

export default function Index({roles, permissionGroups, canManagePermissions}) {
    const [selected, setSelected] = useState(roles[0]?.name || '');
    const role = roles.find(item => item.name === selected);
    const [permissions, setPermissions] = useState(role?.permissions || []);
    const choose = name => { const next = roles.find(item => item.name === name); setSelected(name); setPermissions(next?.permissions || []); };
    const toggle = name => setPermissions(current => current.includes(name) ? current.filter(item => item !== name) : [...current, name]);
    return <Layout><Head title="Roles & Permissions"/><section className="rounded-3xl border border-sky-100 bg-gradient-to-br from-sky-50 via-white to-blue-50 p-6 shadow-sm"><p className="text-sm font-bold text-sky-700">Administration</p><h1 className="mt-1 text-2xl font-black text-slate-900">Roles & permissions</h1></section><div className="mt-5 grid gap-5 lg:grid-cols-[300px_minmax(0,1fr)]"><section className="space-y-3">{roles.map(item => <button type="button" key={item.name} onClick={() => choose(item.name)} className={`w-full rounded-2xl border p-4 text-left ${selected === item.name ? 'border-sky-300 bg-sky-50' : 'border-slate-100 bg-white'}`}><p className="font-bold">{item.name}</p><p className="mt-1 text-sm text-slate-500">{item.permission_count} permissions · {item.user_count} users</p></button>)}</section><section className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">{selected} permissions</h2>{canManagePermissions ? <><div className="mt-5 space-y-5">{permissionGroups.map(group => <fieldset key={group.domain}><legend className="font-bold">{group.domain}</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{group.permissions.map(permission => <label key={permission} className="flex min-w-0 items-center gap-2 rounded-xl border border-slate-100 bg-slate-50 p-2.5 text-sm"><input type="checkbox" checked={permissions.includes(permission)} onChange={() => toggle(permission)}/><span className="break-all">{permission}</span></label>)}</div></fieldset>)}</div><button type="button" className="btn mt-6" onClick={() => router.put(`/administration/roles/${role.id}/permissions`, {permissions}, {preserveScroll: true})}>Save permissions</button></> : <div className="mt-4 flex flex-wrap gap-2">{role?.permissions.map(permission => <span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold" key={permission}>{permission}</span>)}</div>}</section></div></Layout>;
}
