import React from 'react';
import {Head, Link} from '@inertiajs/react';
import Layout from '../../Layouts/AuthenticatedLayout';
import Icon from '../../Components/UI/Icon';
import StatusBadge from '../../Components/UI/StatusBadge';
import courseworkEmpty from '../../assets/edway-empty-coursework.svg';

export default function Index({schoolClass, assignments, subjects}) {
    return <Layout><Head title="Coursework"/>
        <header className="mb-6 rounded-3xl border border-indigo-100 bg-gradient-to-br from-white via-indigo-50/55 to-violet-50 px-6 py-6 shadow-sm sm:px-8"><Link href={`/collaboration/classes/${schoolClass.id}`} className="inline-flex items-center gap-1.5 text-sm font-bold text-indigo-600 transition hover:text-indigo-800 focus:outline-none focus:underline">← Class workspace</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-5"><div className="flex items-start gap-4"><span className="inline-flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-indigo-600 text-white shadow-lg shadow-indigo-200"><Icon name="clipboard" className="h-6 w-6"/></span><div><p className="text-sm font-semibold text-indigo-600">Learning workspace</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Coursework · {schoolClass.name} {schoolClass.section}</h1><p className="mt-2 text-sm leading-6 text-slate-600">{schoolClass.grade_level?.name} · {schoolClass.academic_year?.name}. View only coursework and actions authorized for this class.</p></div></div>{subjects.length > 0 && <div className="flex flex-wrap gap-2">{subjects.map((subject) => <Link className="btn" key={subject.id} href={`/school-classes/${schoolClass.id}/class-subjects/${subject.id}/assignments/create`}><Icon name="clipboard" className="mr-2 h-4 w-4"/>New assignment</Link>)}</div>}</div></header>
        <section><div className="mb-3 flex items-center gap-2"><span className="inline-flex h-8 w-8 items-center justify-center rounded-lg edway-tone-coral text-rose-700"><Icon name="book" className="h-4 w-4"/></span><div><h2 className="font-bold text-slate-900">Assignments</h2><p className="text-sm text-slate-500">Current coursework in this class, with server-authorized actions only.</p></div></div><div className="grid gap-4">{assignments.map((assignment) => <AssignmentCard key={assignment.id} assignment={assignment} schoolClass={schoolClass}/>)}{assignments.length === 0 && <EmptyCoursework/>}</div></section>
    </Layout>;
}

function AssignmentCard({assignment, schoolClass}) { return <Link className="edway-card group block p-5 transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-indigo-300" href={`/school-classes/${schoolClass.id}/class-subjects/${assignment.subject.id}/assignments/${assignment.id}`}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-3"><span className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl edway-tone-lavender text-indigo-700"><Icon name="clipboard" className="h-5 w-5"/></span><div><p className="flex items-center gap-1.5 text-sm font-medium text-slate-500"><Icon name="book" className="h-4 w-4 text-indigo-500"/>{assignment.subject.name}</p><h3 className="mt-1 text-lg font-bold text-slate-900">{assignment.title}</h3><p className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-slate-600"><span className="font-semibold text-slate-800">{assignment.max_points} points</span>{assignment.due_at && <span className="inline-flex items-center gap-1.5"><Icon name="calendar" className="h-4 w-4 text-indigo-500"/>Due {new Date(assignment.due_at).toLocaleString()}</span>}</p></div></div><div className="flex items-center gap-3"><StatusBadge value={assignment.status}/><Icon name="spark" className="h-4 w-4 text-indigo-400 transition group-hover:text-indigo-600"/></div></div></Link>; }
function EmptyCoursework() { return <div className="edway-card flex min-h-64 flex-col items-center justify-center text-center"><img src={courseworkEmpty} alt="" className="h-28 w-40 object-contain"/><h3 className="mt-3 font-bold text-slate-800">No accessible coursework yet</h3><p className="mt-1 max-w-md text-sm leading-6 text-slate-500">Assignments authorized for this class will appear here when available.</p></div>; }
