import React from 'react'; import {Head,useForm} from '@inertiajs/react'; import Layout from '../../Layouts/AuthenticatedLayout';
const Errors=({form})=><>{Object.values(form.errors).map((e,i)=><p key={i} className="text-sm text-red-600">{e}</p>)}</>;
function ClassSubjectsForm({schoolClass,subjects}){const form=useForm({subject_ids:schoolClass.class_subjects.map(x=>x.subject_id)});return <form className="flex min-w-64 gap-2" onSubmit={e=>{e.preventDefault();form.put(`/school-classes/${schoolClass.id}/subjects`)}}><select className="field" multiple value={form.data.subject_ids.map(String)} onChange={e=>form.setData('subject_ids',Array.from(e.target.selectedOptions,o=>Number(o.value)))}>{subjects.map(s=><option value={s.id} key={s.id}>{s.code} · {s.name}</option>)}</select><button className="btn">Save</button></form>}
export default function Index({academicYears,gradeLevels,subjects,schoolClasses,yearStatuses,classStatuses}){
 const year=useForm({name:'',starts_on:'',ends_on:'',status:'planned'}),grade=useForm({name:'',sequence:'',is_active:true}),subject=useForm({code:'',name:'',is_active:true}),klass=useForm({academic_year_id:'',grade_level_id:'',name:'',section:'',status:'planned',capacity:30});
 const submit=(e,f,url)=>{e.preventDefault();f.post(url,{onSuccess:()=>f.reset()})};
 return <Layout><Head title="Academic foundation"/><h1 className="mb-6 text-2xl font-bold">Academic foundation</h1><div className="grid gap-6 lg:grid-cols-2">
 <section className="card"><h2 className="mb-4 text-lg font-semibold">Academic years</h2><form className="grid gap-3" onSubmit={e=>submit(e,year,'/academic-years')}><input className="field" placeholder="2026–2027" value={year.data.name} onChange={e=>year.setData('name',e.target.value)}/><div className="grid grid-cols-2 gap-2"><input className="field" type="date" value={year.data.starts_on} onChange={e=>year.setData('starts_on',e.target.value)}/><input className="field" type="date" value={year.data.ends_on} onChange={e=>year.setData('ends_on',e.target.value)}/></div><select className="field" value={year.data.status} onChange={e=>year.setData('status',e.target.value)}>{yearStatuses.map(x=><option key={x}>{x}</option>)}</select><Errors form={year}/><button className="btn">Add year</button></form><ul className="mt-4 divide-y">{academicYears.map(x=><li className="py-2" key={x.id}>{x.name} <span className="text-sm text-slate-500">· {x.status}</span></li>)}</ul></section>
 <section className="card"><h2 className="mb-4 text-lg font-semibold">Grade levels</h2><form className="flex gap-2" onSubmit={e=>submit(e,grade,'/grade-levels')}><input className="field" placeholder="Grade 1" value={grade.data.name} onChange={e=>grade.setData('name',e.target.value)}/><input className="field w-28" type="number" placeholder="Order" value={grade.data.sequence} onChange={e=>grade.setData('sequence',e.target.value)}/><button className="btn">Add</button></form><Errors form={grade}/><ul className="mt-4 divide-y">{gradeLevels.map(x=><li className="py-2" key={x.id}>{x.sequence}. {x.name}</li>)}</ul></section>
 <section className="card"><h2 className="mb-4 text-lg font-semibold">Subjects</h2><form className="flex gap-2" onSubmit={e=>submit(e,subject,'/subjects')}><input className="field w-32" placeholder="Code" value={subject.data.code} onChange={e=>subject.setData('code',e.target.value)}/><input className="field" placeholder="Subject name" value={subject.data.name} onChange={e=>subject.setData('name',e.target.value)}/><button className="btn">Add</button></form><Errors form={subject}/><ul className="mt-4 divide-y">{subjects.map(x=><li className="py-2" key={x.id}><b>{x.code}</b> · {x.name}</li>)}</ul></section>
 <section className="card"><h2 className="mb-4 text-lg font-semibold">School classes</h2><form className="grid gap-2" onSubmit={e=>submit(e,klass,'/school-classes')}><div className="grid grid-cols-2 gap-2"><select className="field" value={klass.data.academic_year_id} onChange={e=>klass.setData('academic_year_id',e.target.value)}><option value="">Academic year</option>{academicYears.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select className="field" value={klass.data.grade_level_id} onChange={e=>klass.setData('grade_level_id',e.target.value)}><option value="">Grade</option>{gradeLevels.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div><div className="grid grid-cols-2 gap-2"><input className="field" placeholder="Class name" value={klass.data.name} onChange={e=>klass.setData('name',e.target.value)}/><input className="field" placeholder="Section" value={klass.data.section} onChange={e=>klass.setData('section',e.target.value)}/></div><select className="field" value={klass.data.status} onChange={e=>klass.setData('status',e.target.value)}>{classStatuses.map(x=><option key={x}>{x}</option>)}</select><Errors form={klass}/><button className="btn">Add class</button></form></section>
 </div><section className="card mt-6 overflow-x-auto"><h2 className="mb-4 text-lg font-semibold">Classes</h2><table className="w-full text-left"><thead><tr><th>Class</th><th>Year</th><th>Grade</th><th>Status</th><th>Subjects</th><th>Class teacher</th></tr></thead><tbody>{schoolClasses.map(x=><tr className="border-t align-top" key={x.id}><td className="py-3">{x.name} {x.section}</td><td>{x.academic_year.name}</td><td>{x.grade_level.name}</td><td>{x.status}</td><td><ClassSubjectsForm schoolClass={x} subjects={subjects}/></td><td>{x.teacher_assignments[0]?.teacher_profile.user.name||'—'}</td></tr>)}</tbody></table></section></Layout>;
}
