import React, {useState} from 'react';
import {Head, Link, useForm} from '@inertiajs/react';
import Guest from '../../Layouts/GuestLayout';
import Icon from '../../Components/UI/Icon';

export default function Login() {
    const form = useForm({email: '', password: '', remember: false});
    const [passwordVisible, setPasswordVisible] = useState(false);
    const submit = (event) => {
        event.preventDefault();
        form.post('/login', {onFinish: () => form.reset('password')});
    };

    return <Guest title="Welcome back"><Head title="Login"/><form onSubmit={submit} className="space-y-5"><div><label htmlFor="email" className="mb-2 block text-sm font-bold text-slate-800">Email address</label><div className="relative"><Icon name="mail" className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input id="email" className="field login-field-with-leading-icon" type="email" placeholder="Enter your email" value={form.data.email} onChange={(event) => form.setData('email', event.target.value)} autoComplete="username" aria-invalid={Boolean(form.errors.email)} aria-describedby={form.errors.email ? 'email-error' : undefined} required/></div>{form.errors.email && <p id="email-error" className="mt-2 text-sm font-medium text-red-700" role="alert">{form.errors.email}</p>}</div><div><div className="mb-2 flex items-center justify-between gap-3"><label htmlFor="password" className="block text-sm font-bold text-slate-800">Password</label><Link className="text-xs font-bold text-[#075ca8] hover:text-[#06487f] focus:outline-none focus:ring-2 focus:ring-[#075ca8] focus:ring-offset-2" href="/forgot-password">Forgot password?</Link></div><div className="relative"><Icon name="lock" className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input id="password" className="field login-field-with-leading-icon login-field-with-trailing-action" type={passwordVisible ? 'text' : 'password'} placeholder="Enter your password" value={form.data.password} onChange={(event) => form.setData('password', event.target.value)} autoComplete="current-password" aria-invalid={Boolean(form.errors.password)} aria-describedby={form.errors.password ? 'password-error' : undefined} required/><button type="button" onClick={() => setPasswordVisible((visible) => !visible)} className="absolute right-2 top-1/2 -translate-y-1/2 rounded-lg p-2 text-slate-400 transition hover:bg-slate-100 hover:text-[#075ca8] focus:outline-none focus:ring-2 focus:ring-[#075ca8]" aria-label={passwordVisible ? 'Hide password' : 'Show password'}><Icon name={passwordVisible ? 'eye-off' : 'eye'} className="h-4 w-4"/></button></div>{form.errors.password && <p id="password-error" className="mt-2 text-sm font-medium text-red-700" role="alert">{form.errors.password}</p>}</div><label className="flex items-center gap-2 text-sm font-medium text-slate-600"><input type="checkbox" checked={form.data.remember} onChange={(event) => form.setData('remember', event.target.checked)} className="h-4 w-4 rounded border-slate-300 text-[#075ca8] focus:ring-[#075ca8]"/>Remember me</label><button className="btn w-full rounded-xl bg-[#082f63] py-3 font-bold hover:bg-[#06487f]" disabled={form.processing}>{form.processing ? 'Signing in…' : 'Sign in'}</button></form></Guest>;
}
